### ISSUE TITLE
Kmz with empty coordinates 

### ISSUE THREAD

**Issue by MRdima98** [googlemaps/android-maps-utils#1228]
#### Summary

If a kmz or kml has a empty coordinate it will cause java.land.ArrayIndexOutOfBoundsException

#### Expected behavior

The file should be parsed successfully, it on the server in Rails

#### Observed behavior

If a kmz or kml has a empty coordinate it will cause java.land.ArrayIndexOutOfBoundsException, this is possible due to converToLatLngAlt that does not check if there are any positions

#### Environment details

1. Pocophone f1
2. minSdkVersion 21, targetSdkVersion 31
3. Latest stable

#### Steps to reproduce

Pick a kmz, remove coordinates from a coordinate tag and the parse the file
```
            KmlLayer kmlLayer = new KmlLayer(mMap, kml_input, getContext());
```
#### Stack trace
```
Process: com.engim.serviziogpstracker, PID: 14417
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
at com.google.maps.android.data.kml.KmlFeatureParser.convertToLatLngAlt(KmlFeatureParser.java:435)
at com.google.maps.android.data.kml.KmlFeatureParser.convertToLatLngAlt(KmlFeatureParser.java:423)
at com.google.maps.android.data.kml.KmlFeatureParser.convertToLatLngAltArray(KmlFeatureParser.java:411)
at com.google.maps.android.data.kml.KmlFeatureParser.createLineString(KmlFeatureParser.java:261)
at com.google.maps.android.data.kml.KmlFeatureParser.createGeometry(KmlFeatureParser.java:193)
at com.google.maps.android.data.kml.KmlFeatureParser.createPlacemark(KmlFeatureParser.java:100)
at com.google.maps.android.data.kml.KmlContainerParser.setContainerPlacemark(KmlContainerParser.java:176)
at com.google.maps.android.data.kml.KmlContainerParser.assignPropertiesToContainer(KmlContainerParser.java:108)
at com.google.maps.android.data.kml.KmlContainerParser.assignPropertiesToContainer(KmlContainerParser.java:100)
at com.google.maps.android.data.kml.KmlContainerParser.createContainer(KmlContainerParser.java:67)
at com.google.maps.android.data.kml.KmlParser.parseKml(KmlParser.java:89)
at com.google.maps.android.data.kml.KmlLayer.parseKml(KmlLayer.java:189)
at com.google.maps.android.data.kml.KmlLayer.<init>(KmlLayer.java:174)
at com.google.maps.android.data.kml.KmlLayer.<init>(KmlLayer.java:79)
at com.engim.serviziogpstracker.navigator.NavigatorFragment.drawStreetmap(NavigatorFragment.java:327)
at com.engim.serviziogpstracker.navigator.NavigatorFragment.loadStreetmaps(NavigatorFragment.java:315)
at com.engim.serviziogpstracker.navigator.NavigatorFragment.access$1700(NavigatorFragment.java:92)
at com.engim.serviziogpstracker.navigator.NavigatorFragment$3.onReceive(NavigatorFragment.java:712)
at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:224)
at android.app.ActivityThread.main(ActivityThread.java:7562)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by wangela** [comment]
If you would like to upvote the priority of this issue, please comment below or react on the original post above with :+1: so we can see what is popular when we triage.
--------

@MRdima98 Thank you for opening this issue. 🙏
Please check out these other resources that might help you get to a resolution in the meantime:

- [Check the issue tracker](https://developers.google.com/maps/support/#issue_tracker) - bugs and feature requests for Google Maps Platform APIs and SDKs
- [Open a support case](https://developers.google.com/maps/support#contact-maps-support) - Get 1:1 support in Cloud Console.
- [Discord](https://discord.gg/fHTDmZe9En) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag


_This is an automated message, feel free to ignore._

**Comment by skw4223** [comment]
May I handle this issue? please assign to me~ I'll create PR soon!
