### ISSUE TITLE
Null Marker returned with onMarkerClick

### ISSUE THREAD

**Issue by rusxakep** [googlemaps/android-maps-utils#336]
**Summary:** 

NPE

**Steps to reproduce:** 

Create simple map with some cluster and markers, fast move device to landscape and back and try to touch cluster or person markers in same time. Application crash with NPE very soon.

**Expected behavior:** 

No NPE

**Observed behavior:** 

FATAL EXCEPTION: main
                                     java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.maps.model.LatLng xxx' on a null object reference
......
                                         at com.google.maps.android.clustering.view.DefaultClusterRenderer$1.onMarkerClick(DefaultClusterRenderer.java:145)
                                         at com.google.maps.android.MarkerManager.onMarkerClick(MarkerManager.java:103)
                                         at com.google.maps.android.clustering.ClusterManager.onMarkerClick(ClusterManager.java:207)
                                         at com.google.android.gms.maps.GoogleMap$2.zza(Unknown Source)
                                         at com.google.android.gms.maps.internal.zzu$zza.onTransact(Unknown Source)
                                         at android.os.Binder.transact(Binder.java:387)
                                         at zx.a(:com.google.android.gms.DynamiteModulesB:84)
                                         at maps.ad.T.b(Unknown Source)
                                         at maps.D.c.a(Unknown Source)
                                         at maps.V.k.a(Unknown Source)
                                         at maps.V.u.d(Unknown Source)
                                         at maps.V.P.onSingleTapConfirmed(Unknown Source)
                                         at maps.z.e$b.onSingleTapConfirmed(Unknown Source)
                                         at maps.z.c$a.handleMessage(Unknown Source)
                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                         at android.os.Looper.loop(Looper.java:148)
                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Device and Android version:** 

Nexus 5 hardware device with Android 6.0.1 and Google Maps 10.0.1 library (google-map-utils v0.4.4)

**Screenshots:** 

No screenshorts.

**Comment by jeffdgr8** [comment]
This may have been fixed with my pull request which was merged: https://github.com/googlemaps/android-maps-utils/pull/321 Can you confirm?
