### ISSUE TITLE
android.view.InflateException: Binary XML file line #17: Error inflating class fragment

### ISSUE THREAD

**Issue by ff-frida** [googlemaps/android-maps-utils#376]
Mobile Information: 'model: QMobile T50/version: 4.4.3/sdk: 19'

Thread Name: 'main'
Back traces starts.
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.infreewifi.cct/com.mobile.freewifi.activity.WifiMapActivity}: android.view.InflateException: Binary XML file line #17: Error inflating class fragment
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2281)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2331)
	at android.app.ActivityThread.access$800(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1225)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5285)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:937)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:753)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class fragment
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:295)
	at android.app.Activity.setContentView(Activity.java:1947)
	at com.mobile.freewifi.activity.BaseMapActivity.onCreate(BaseMapActivity.java:36)
	at android.app.Activity.performCreate(Activity.java:5341)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1099)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225)
	... 11 more
Caused by: java.lang.NullPointerException
	at ijn.a(:com.google.android.gms:1227)
	at ijm.b(:com.google.android.gms:197)
	at gzr.logEvent(:com.google.android.gms:1216)
	at gzr.logEvent(:com.google.android.gms:60)
	at com.google.android.chimera.container.DebugLogger.logEvent(:com.google.android.gms:65)
	at com.google.android.chimera.container.ConfigurationManager.loadModuleByModuleId(:com.google.android.gms:546)
	at gzt.a(:com.google.android.gms:74)
	at com.google.android.gms.maps.internal.CreatorImpl.a(:com.google.android.gms:1112)
	at com.google.android.gms.maps.internal.CreatorImpl.newMapFragmentDelegate(:com.google.android.gms:95)
	at ruh.onTransact(:com.google.android.gms:62)
	at android.os.Binder.transact(Binder.java:384)
	at com.google.android.gms.maps.internal.zzc$zza$zza.zzag(Unknown Source)
                                                     zzbpf
	at com.google.android.gms.maps.SupportMapFragment$zzb.zzbow(Unknown Source)
	at com.google.android.gms.maps.SupportMapFragment$zzb.zza(Unknown Source)
                                                       setActivity
                                                       getMapAsync
                                                       zza
	at com.google.android.gms.dynamic.zza.zzbbt(Unknown Source)
                                       zznd
                                       zza
                                       zza
                                       onInflate
                                       onCreate
                                       onCreateView
                                       zza
                                       zza
                                       zza
                                       zza
	at com.google.android.gms.dynamic.zza.zzbbt(Unknown Source)
                                       zznd
                                       zza
                                       zza
                                       onInflate
                                       onCreate
                                       onCreateView
                                       zza
                                       zza
                                       zza
                                       zza
	at com.google.android.gms.maps.SupportMapFragment.onInflate(Unknown Source)
	at android.support.v4.app.Fragment.onInflate(Fragment.java:1142)
	at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2287)
	at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
	at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:357)
	at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:31)
	at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:80)
                                            onCreateView
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:689)
	... 22 more

-----------------------------------------------------------
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/activity_google_map"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <include layout="@layout/common_title_layout" />

    <LinearLayout
        android:id="@+id/map_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:visibility="visible">

        <fragment xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:map="http://schemas.android.com/apk/res-auto"
            android:id="@+id/map"
            android:name="com.google.android.gms.maps.SupportMapFragment"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

        </fragment>
    </LinearLayout>

    <RelativeLayout
        android:visibility="gone"
        android:id="@+id/check_gps_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/color_f6f6f6"
        >
        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            android:layout_centerInParent="true"
            >
            <ImageView
                android:layout_width="96dp"
                android:layout_height="96dp"
                android:src="@drawable/ic_map_setting_location"
                android:layout_gravity="center"
                />
            <TextView
                android:id="@+id/map_oops"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal"
                android:layout_marginTop="12dp"
                android:textSize="12sp"
                android:textColor="@color/color_889499"
                android:text="@string/map_cannot_get_your_location"/>
            <TextView
                android:id="@+id/map_setting_text"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal"
                android:layout_marginTop="6dp"
                android:textSize="12sp"
                android:textColor="@color/color_889499"
                android:text="@string/map_check_gps"
                />
            <Button
                android:id="@+id/map_setting"
                android:layout_width="160dp"
                android:layout_height="36dp"
                android:layout_gravity="center"
                android:layout_marginTop="48dp"
                android:background="@drawable/map_setting_btn_selector"
                android:gravity="center"
                android:text="@string/setting"
                android:textColor="@drawable/connect_txt_selector"
                android:textSize="12sp" />

        </LinearLayout>
    </RelativeLayout>
</LinearLayout>

-----------------------------------------------------------------------------
Probability of occurrence 0.001

**Comment by AhmedMousa7** [comment]
you must put this in your manifest:

`<meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />

        <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="@string/google_places_api_key" />`

**Comment by rongdongliu** [comment]
I follow this configuration, and this error occurs again

**Comment by Fasfemi** [comment]
change android:name="com.google.android.gms.maps.SupportMapFragment" to "class="com.google.android.gms.maps.MapFragment""

**Comment by d3x773r** [comment]
check this out

```
<ImageView
            android:layout_width="96dp"
            android:layout_height="96dp"
            **app:srcCompat="@drawable/ic_map_setting_location"**
            android:layout_gravity="center"
            />
```
use:  **app:srcCompat=" "**
rather than:  **android:src=" "**

and try again.
Hope this helps.

**Comment by etuna** [comment]
Hi,

Check your fragment,but you need to also check that your context should implement the fragment's listener.

Best

**Comment by jm009** [comment]
Hi peach-djf,
sorry, I don't have the solution...  I have a similar issue :-)
Were you able to solve this?
Best regards and thank you

**Comment by DeebanT2S** [comment]
Hi, 

Use FrameLayout in xml instead of using fragment

**Comment by maxmelnyk** [comment]
Just check, that your <meta-data /> in Manifest are in <application>

**Comment by NeginAryapour** [comment]
I have the Same issue... any news?

**Comment by pratik2315** [comment]
In my case it was throwing a exception and telling me fragment should have unique id or tag. i just gave the fragment tag in xml a unique id and my error was gone

**Comment by sureshchouhan2009** [comment]
In my case i was wrong at manifest side.

**Comment by sachinssoni98** [comment]
I was also facing a similar error. I have just given id to fragment and my error has gone.

**Comment by azizismoilov97** [comment]
Is there a solution here

**Comment by louis5md** [comment]
I have a similiar problem but with a basic google maps activity. The solution for my problem is to change android:exported="true" in Manifest for maps activity
