### ISSUE TITLE
java.lang.RuntimeException: Package manager has died

### ISSUE THREAD

**Issue by ff-frida** [googlemaps/android-maps-utils#382]
```
java.lang.RuntimeException: Package manager has died
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:207)
	at lz.a(:com.google.android.gms.DynamiteModulesB:713)
	at lo.a(:com.google.android.gms.DynamiteModulesB:3285)
	at pf.a(:com.google.android.gms.DynamiteModulesB:10829)
	at oq.a(:com.google.android.gms.DynamiteModulesB:115)
	at pk.a(:com.google.android.gms.DynamiteModulesB:449)
	at od.a(:com.google.android.gms.DynamiteModulesB:40)
	at se.a(:com.google.android.gms.DynamiteModulesB:236)
	at rn.handleMessage(:com.google.android.gms.DynamiteModulesB:246)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5371)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: android.os.DeadObjectException
	at android.os.BinderProxy.transact(BinderProxy.java)
	at android.content.pm.IPackageManager$Stub$Proxy.getApplicationInfo(IPackageManager.java:1565)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:202)
	... 16 more
android.os.DeadObjectException
	at android.os.BinderProxy.transact(BinderProxy.java)
	at android.content.pm.IPackageManager$Stub$Proxy.getApplicationInfo(IPackageManager.java:1565)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:202)
	at lz.a(:com.google.android.gms.DynamiteModulesB:713)
	at lo.a(:com.google.android.gms.DynamiteModulesB:3285)
	at pf.a(:com.google.android.gms.DynamiteModulesB:10829)
	at oq.a(:com.google.android.gms.DynamiteModulesB:115)
	at pk.a(:com.google.android.gms.DynamiteModulesB:449)
	at od.a(:com.google.android.gms.DynamiteModulesB:40)
	at se.a(:com.google.android.gms.DynamiteModulesB:236)
	at rn.handleMessage(:com.google.android.gms.DynamiteModulesB:246)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5371)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by JeffZane** [comment]
Same stacktrace for me.

**Comment by abiemann** [comment]
Same

**Comment by yhartanto** [comment]
Is there any update on this issue, this causes a lot of crashes for us.

**Comment by jiyouliang** [comment]
The Same for me, but It normal when I Running the ApiDemo on Api 2
<img width="247" alt="screenshot" src="https://user-images.githubusercontent.com/19160100/54129354-06dda080-4449-11e9-894d-fff61e4ac70f.png">
6.
