### ISSUE TITLE
android.content.ActivityNotFoundException: No Activity found to handle Intent 

### ISSUE THREAD

**Issue by rongdongliu** [googlemaps/android-maps-utils#397]
Mobile Information: 'model: Primo NF2+/version: 6.0/sdk: 23'
Build fingerprint: 'alps/6.0/MRA58K/1471349270:user/test-keys'
Runtime Information: 'start: 20170514235336/maxheap: 134217728'
```Process Name: 'com.dolphinwifi.cct'
Thread Name: 'main'
Back traces starts.
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=geo:23.8884281151483,90.41885208338499?z=16.142334&q=23.888428,90.418852(i2B91 - Noyon) flg=0x10000000 pkg=com.google.android.apps.maps }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
	at android.app.ContextImpl.startActivity(ContextImpl.java:682)
	at android.app.ContextImpl.startActivity(ContextImpl.java:664)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
	at com.google.maps.api.android.lib6.impl.ay.a(:com.google.android.gms.DynamiteModulesB:118)
	at com.google.maps.api.android.lib6.impl.ay.a(:com.google.android.gms.DynamiteModulesB:109)
	at com.google.maps.api.android.lib6.impl.cz.onClick(:com.google.android.gms.DynamiteModulesB:182)
	at android.view.View.performClick(View.java:5265)
	at android.view.View$PerformClick.run(View.java:21534)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5728)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Back traces ends.
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---


```

**Comment by stephenmcd** [comment]
This doesn't appear to be related to this library. Please re-open if you can clarify further.
