### ISSUE TITLE
java.lang.SecurityException: Unable to find app for caller android.app.ApplicationThreadProxy@42a1b120 (pid=10194) when binding service Intent { act=com.google.android.gms.clearcut.service.START pkg=com.google.android.gms }

### ISSUE THREAD

**Issue by rongdongliu** [googlemaps/android-maps-utils#423]
Basic Information: 'pid: 10194/tid: 10194/logver: 2/time: 20170903104407/cpu: armeabi-v7a/cpu hardware: mt6592'
Mobile Information: 'model: 8x-1000/version: 4.4.2/sdk: 19'

```
Back traces starts.
java.lang.SecurityException: Unable to find app for caller android.app.ApplicationThreadProxy@42a1b120 (pid=10194) when binding service Intent { act=com.google.android.gms.clearcut.service.START pkg=com.google.android.gms }
	at android.os.Parcel.readException(Parcel.java:1465)
	at android.os.Parcel.readException(Parcel.java:1419)
	at android.app.ActivityManagerProxy.bindService(ActivityManagerNative.java:3129)
	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1671)
	at android.app.ContextImpl.bindService(ContextImpl.java:1640)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:517)
	at om.a(:com.google.android.gms.DynamiteModulesB@11509036:45)
	at ol.a(:com.google.android.gms.DynamiteModulesB@11509036:15)
	at nm.a(:com.google.android.gms.DynamiteModulesB@11509036:66)
	at nm.a(:com.google.android.gms.DynamiteModulesB@11509036:99)
	at lo.a(:com.google.android.gms.DynamiteModulesB@11509036:34)
	at lv.run(:com.google.android.gms.DynamiteModulesB@11509036:10)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at qd.run(:com.google.android.gms.DynamiteModulesB@11509036:6)
	at java.lang.Thread.run(Thread.java:841)
Back traces ends.
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
meminfo:
MemTotal:        2016732 kB
MemFree:          932968 kB
Buffers:           34524 kB
Cached:           156524 kB
SwapCached:       115424 kB
Active:           333504 kB
Inactive:         299948 kB
Active(anon):     250916 kB
Inactive(anon):   192660 kB
Active(file):      82588 kB
Inactive(file):   107288 kB
Unevictable:           0 kB
Mlocked:               0 kB
HighTotal:       1525752 kB
HighFree:         920996 kB
LowTotal:         490980 kB
LowFree:           11972 kB
SwapTotal:       1048572 kB
SwapFree:         757272 kB
Dirty:                72 kB
Writeback:             0 kB
AnonPages:        405176 kB
Mapped:            78892 kB
Shmem:              1028 kB
Slab:              50152 kB
SReclaimable:      23064 kB
SUnreclaim:        27088 kB
KernelStack:       12232 kB
PageTables:        17560 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     2056936 kB
Committed_AS:   22045428 kB
VmallocTotal:     499712 kB
VmallocUsed:      283216 kB
VmallocChunk:      81600 kB

--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
status:
Name:	dolphinwifi.cct
State:	R (running)
Tgid:	10194
Pid:	10194
PPid:	161
TracerPid:	0
Uid:	10134	10134	10134	10134
Gid:	10134	10134	10134	10134
FDSize:	256
Groups:	1015 1028 3003 50134 
VmPeak:	  732812 kB
VmSize:	  684516 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	   79520 kB
VmRSS:	   55328 kB
VmData:	  136160 kB
VmStk:	     136 kB
VmExe:	       8 kB
VmLib:	   48188 kB
VmPTE:	     358 kB
VmSwap:	   14144 kB
Threads:	91
SigQ:	0/15747
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000009204
SigIgn:	0000000000000000
SigCgt:	00000002000094f8
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	ffffffe000000000
Cpus_allowed:	ff
Cpus_allowed_list:	0-7
voluntary_ctxt_switches:	295156
nonvoluntary_ctxt_switches:	223425

--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
Dalvik:
MaxMemory: 134217728 TotalMemory: 21458944 FreeMemory: 7494488
```

**Comment by barbeau** [comment]
@rongdongliu looks like this is an issue with Google Play Services (Google Maps), not the utility library, so I'm closing this issue out.

**Comment by rongdongliu** [comment]
thank

**Comment by yurii-diachenko** [comment]
nice workaround...
