### ISSUE TITLE
kml: Whitespace in <color> throws exception

### ISSUE THREAD

**Issue by akirmse** [googlemaps/android-maps-utils#427]
Extra whitespace in a <color> tag will throw a NumberFormatException from Color.parseColor

For example:

         <color>ff0098e6 </color> 

It's not immediately obvious from the XML and KML specs whether this is valid, but in any case, it would make sense to trim the color string before attempting to parse it.

A sample KML with this extra whitespace is https://rmgsc.cr.usgs.gov/outgoing/GeoMAC/ActiveFirePerimeters.kml

Here is a stack trace:

Caused by: java.lang.NumberFormatException: Invalid long: "ff0098e6 "
                                                                                 at java.lang.Long.invalidLong(Long.java:124)
                                                                                 at java.lang.Long.parse(Long.java:361)
                                                                                 at java.lang.Long.parseLong(Long.java:352)
                                                                                 at android.graphics.Color.parseColor(Color.java:211)
                                                                                 at com.google.maps.android.data.kml.KmlStyle.setOutlineColor(KmlStyle.java:334)
                                                                                 at com.google.maps.android.data.kml.KmlStyleParser.createLineStyle(KmlStyleParser.java:195)
                                                                                 at com.google.maps.android.data.kml.KmlStyleParser.createStyle(KmlStyleParser.java:55)
                                                                                 at com.google.maps.android.data.kml.KmlContainerParser.setContainerStyle(KmlContainerParser.java:148)
                                                                                 at com.google.maps.android.data.kml.KmlContainerParser.assignPropertiesToContainer(KmlContainerParser.java:91)
                                                                                 at com.google.maps.android.data.kml.KmlContainerParser.createContainer(KmlContainerParser.java:52)
                                                                                 at com.google.maps.android.data.kml.KmlParser.parseKml(KmlParser.java:74)
                                                                                 at com.google.maps.android.data.kml.KmlLayer.<init>(KmlLayer.java:47)

**Comment by broady** [comment]
@csadams is this valid KML?

**Comment by csadams** [comment]
It's certainly not good KML, but I'm not sure if it's technically invalid or not... I suspect that it is not valid. 

The KML spec and schema specify a KML color to be 8 characters (4 hex values), like: AABBGGRR. So anything other than the 8 characters in the <color> tag is not good... but I'm not sure how XML handles things like that... if extra white space makes it invalid or not.  I would expect/hope so.  Even if it's invalid, it would be nice if we could gracefully accept it and remove the whitespace. 

It would also be nice to reach out to the KML owners to make sure they're aware of the issue, and find out if it's a mistake in a custom KML generation script, or if it's being generated by a more commonly used tool.

**Comment by akirmse** [comment]
(Even if it isn't valid KML, a library shouldn't throw unchecked exceptions
and bring down the whole app.)

**Comment by akirmse** [comment]
Yes, I've asked the authors (a government agency) to fix their KML.  It may be awhile.

BTW I've since found at least one other scenario (<coordinates> with non-numeric characters) that also throws an unchecked exception.  It would be good to audit the whole library and make sure that bad input doesn't crash.

**Comment by akirmse** [comment]
I don't think anything has been done, so the bug is still valid.

**Comment by broady** [comment]
un-stale
