### ISSUE TITLE
Crash when clicking on non-KML marker with KML layer enabled

### ISSUE THREAD

**Issue by akirmse** [googlemaps/android-maps-utils#430]
If the app enables a KML layer and also adds its own Markers to the map, then android-maps-utils will crash when one of those Markers is clicked.

The problem appears to be that the library installs global onClickListeners for marker, polygon, and polyline clicks:

https://github.com/googlemaps/android-maps-utils/blob/master/library/src/com/google/maps/android/data/Layer.java#L89

and then assumes that all clicks are on KML objects.  The resulting stack trace is below.  This needs to be redesigned so that the library receives click events from the app, and passes through any that don't belong to it.

10-25 10:04:26.491 10229-10229/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.mountainside.peakbagger, PID: 10229
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                       at java.io.StringReader.<init>(StringReader.java:50)
                                                       at android.text.HtmlToSpannedConverter.convert(Html.java:746)
                                                       at android.text.Html.fromHtml(Html.java:242)
                                                       at android.text.Html.fromHtml(Html.java:185)
                                                       at com.google.maps.android.a.h$1.b(Renderer.java:908)
                                                       at com.google.android.gms.maps.o.b(Unknown Source:7)
                                                       at com.google.android.gms.maps.a.al.onTransact(Unknown Source:40)
                                                       at android.os.Binder.transact(Binder.java:604)
                                                       at gl.a(:com.google.android.gms.DynamiteModulesB@11518440:10)
                                                       at com.google.android.gms.maps.internal.n.b(:com.google.android.gms.DynamiteModulesB@11518440:18)
                                                       at com.google.maps.api.android.lib6.impl.bw.a(:com.google.android.gms.DynamiteModulesB@11518440:54)
                                                       at com.google.maps.api.android.lib6.impl.bw.a(:com.google.android.gms.DynamiteModulesB@11518440:73)
                                                       at com.google.maps.api.android.lib6.gmm6.api.e.a(:com.google.android.gms.DynamiteModulesB@11518440:37)
                                                       at com.google.maps.api.android.lib6.gmm6.api.g.c(:com.google.android.gms.DynamiteModulesB@11518440:153)
                                                       at com.google.maps.api.android.lib6.impl.cz.g(:com.google.android.gms.DynamiteModulesB@11518440:239)
                                                       at com.google.maps.api.android.lib6.impl.db.b(:com.google.android.gms.DynamiteModulesB@11518440:27)
                                                       at com.google.maps.api.android.lib6.gmm6.api.e.a(:com.google.android.gms.DynamiteModulesB@11518440:64)
                                                       at com.google.maps.api.android.lib6.gmm6.vector.m.a(:com.google.android.gms.DynamiteModulesB@11518440:45)
                                                       at com.google.maps.api.android.lib6.gmm6.vector.af.c(:com.google.android.gms.DynamiteModulesB@11518440:194)
                                                       at com.google.maps.api.android.lib6.gmm6.vector.cr.onSingleTapConfirmed(:com.google.android.gms.DynamiteModulesB@11518440:28)
                                                       at com.google.maps.api.android.lib6.impl.gesture.h.onSingleTapConfirmed(:com.google.android.gms.DynamiteModulesB@11518440:125)
                                                       at com.google.maps.api.android.lib6.impl.gesture.d.handleMessage(:com.google.android.gms.DynamiteModulesB@11518440:26)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by akirmse** [comment]
My mistake.. while that code I referenced previously is problematic because it installs global handlers, it's not the immediate cause of the crash.  It's actually the global infoWindowAdapter that's installed here:

https://github.com/googlemaps/android-maps-utils/blob/master/library/src/com/google/maps/android/data/Renderer.java#L896

That overrides any info window adapter set by the app, and in particular, if the marker doesn't have a title set, it crashes.

**Comment by jeffdgr8** [comment]
This is fixed in my pull request https://github.com/googlemaps/android-maps-utils/pull/380.

**Comment by jeffdgr8** [comment]
This is still an issue until https://github.com/googlemaps/android-maps-utils/pull/380 is merged.
