### ISSUE TITLE
How to get reference to recently clicked cluster item after reclustering?

### ISSUE THREAD

**Issue by youlovejohnny** [googlemaps/android-maps-utils#505]
**Summary:** 
I'm trying to highlight my clicked cluster item. It works.
But when i zoom out and zoom in back i got NullPointerException.
So, my question: How to get reference to marker which i want tot unhighlight?

**Steps to reproduce:** 

1. Zoom in to see every item
2. Click on item to highlight it.
Also, you can click other items and previously selected item will be unhighlighted. New item will highlighted. 
3. Zoom out to see clusters.
4. Zoom in back. 
Now you can see, that early clicked item highlighted. But when you're trying to select an other item, you will get NPE.

**Expected behavior:** 
I want to get reference to an old marker to unhighlight it.

My code: 
`class CustomClusterRenderrer(val context: Context,val map: GoogleMap, val clusterManager: ClusterManager<CustomMarker>): DefaultClusterRenderer<CustomMarker>(context,map,clusterManager) {

    var imageHelper: ImageHelper = ImageHelper(context)
    private val inactiveMarkerIcon = imageHelper.getBitmapFromDrawable(ContextCompat.getDrawable(context,R.drawable.ic_inactive)!!)
    private val activeMarkerIcon = imageHelper.getBitmapFromDrawable(ContextCompat.getDrawable(context,R.drawable.ic_active)!!)

    var selectedMarker: CustomMarker? = null
    var unselectedMarker: CustomMarker? = null
    var selectedName = "" // unique string 

    init {
        minClusterSize = 2
    }

    /**
     * Here we describe the properties of the markers that will be shown after disclosure of a cluster.
     * */
    override fun onBeforeClusterItemRendered(item: CustomMarker, markerOptions: MarkerOptions) {
        super.onBeforeClusterItemRendered(item, markerOptions)

        if (item.title == selectedName) {
            selectedMarker = null
            unselectedMarker = null
           markerOptions.icon(BitmapDescriptorFactory.fromBitmap(activeMarkerIcon))
            selectMarker(item)
        } else {
            markerOptions.icon(BitmapDescriptorFactory.fromBitmap(inactiveMarkerIcon))
        }
    }

 // setting custom listener below
    override fun setOnClusterItemClickListener(listener: ClusterManager.OnClusterItemClickListener<CustomMarker>?) {
        super.setOnClusterItemClickListener(onClusterItemClickListener)
    }

    private val onClusterItemClickListener = ClusterManager.OnClusterItemClickListener<CustomMarker> { customMarker ->
        if (customMarker.title == selectedName)  false  // same marker pressed
        if (selectedMarker == null) { 
            selectMarker(customMarker)
        } else {
            unselectMarker(customMarker)
            selectMarker(customMarker)
        }
        false
    }

    private fun selectMarker(customMarker: CustomMarker) {
        selectedName = customMarker.title
        selectedMarker = customMarker
        val marker = getMarker(customMarker)
        marker!!.setIcon(BitmapDescriptorFactory.fromBitmap(activeMarkerIcon)) // NPE here
    }

  
    private fun unselectMarker(customMarker: CustomMarker) {
        customMarker.selected = false
        unselectedMarker = selectedMarker
        val unsMarker = getMarker(unselectedMarker)
        unsMarker!!.setIcon(BitmapDescriptorFactory.fromBitmap(inactiveMarkerIcon))
    }

}`

Stacktrace: 
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ginzago.android, PID: 21616
    kotlin.KotlinNullPointerException
        at com.ginzago.android.view.screens.home.catalog_google.CustomClusterRenderrer.selectMarker(CustomClusterRenderrer.kt:81)
        at com.ginzago.android.view.screens.home.catalog_google.CustomClusterRenderrer.onBeforeClusterItemRendered(CustomClusterRenderrer.kt:54)
        at com.ginzago.android.view.screens.home.catalog_google.CustomClusterRenderrer.onBeforeClusterItemRendered(CustomClusterRenderrer.kt:16)
        at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.perform(DefaultClusterRenderer.java:843)
        at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.access$2100(DefaultClusterRenderer.java:805)
        at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask(DefaultClusterRenderer.java:644)
        at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage(DefaultClusterRenderer.java:615)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by youlovejohnny** [comment]
Solve my problem by changing 

`override fun onBeforeClusterItemRendered(item: CustomMarker, markerOptions: MarkerOptions) {
    super.onBeforeClusterItemRendered(item, markerOptions)

    if (item.title == selectedName) {
        selectedMarker = null
        unselectedMarker = null
       markerOptions.icon(BitmapDescriptorFactory.fromBitmap(activeMarkerIcon))
        selectMarker(item)
    } else {
        markerOptions.icon(BitmapDescriptorFactory.fromBitmap(inactiveMarkerIcon))
    }
}`

to 
`override fun onBeforeClusterItemRendered(item: CustomMarker, markerOptions: MarkerOptions) {
    super.onBeforeClusterItemRendered(item, markerOptions)

    if (item.title == selectedName) {
        selectedMarker = null
        unselectedMarker = null
       markerOptions.icon(BitmapDescriptorFactory.fromBitmap(activeMarkerIcon))
    selectedMarker = item
    } else {
        markerOptions.icon(BitmapDescriptorFactory.fromBitmap(inactiveMarkerIcon))
    }
}`

But question is open: Why i cant get reference to marker?
