### ISSUE TITLE
Unable to parse kml with gx:LatLonQuad node

### ISSUE THREAD

**Issue by acespring78** [googlemaps/android-maps-utils#650]
Hello. I have a kml file that uses the `xmlns:gx="http://www.google.com/kml/ext/2.2"` namespace and uses the `gx:LatLonQuad` node with the `coordinates` defining the lat/lon coordinates of the box, instead of `LatLonBox`

When loading this kml file to `KmlLayer`, it throws an exception because I believe it doesn't read the `gx:LatLonQuad` node, but instead is looking for `LatLonBox` to parse the `north`, `south`, `east`, and `west` nodes. The following exception trace is as follows:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
        at com.google.maps.android.data.kml.KmlFeatureParser.createLatLngBounds(KmlFeatureParser.java:452)
        at com.google.maps.android.data.kml.KmlFeatureParser.createGroundOverlay(KmlFeatureParser.java:150)
        at com.google.maps.android.data.kml.KmlContainerParser.assignPropertiesToContainer(KmlContainerParser.java:113)
        at com.google.maps.android.data.kml.KmlContainerParser.createContainer(KmlContainerParser.java:67)
        at com.google.maps.android.data.kml.KmlParser.parseKml(KmlParser.java:89)
        at com.google.maps.android.data.kml.KmlLayer.parseKml(KmlLayer.java:189)
        at com.google.maps.android.data.kml.KmlLayer.<init>(KmlLayer.java:156)
        at com.google.maps.android.data.kml.KmlLayer.<init>(KmlLayer.java:79)
```

This kml file works when loading to Google Earth by the way.

Is there plans to support `gx:LatLonQuad` in later releases?

**Comment by arriolac** [comment]
Thanks for reporting. This was not something we were planning on adding, however, contributions are certainly welcome to get this working.

**Comment by arriolac** [comment]
Would you mind sharing an example KML file / snippet in case someone wants to take this on?

**Comment by acespring78** [comment]
Here's a sample. The `icon` field can be replaced with any image file, but the key item here is the `gx:LatLonQuad` node and the absence of the `LatLonBox`

```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">
	<Document>
		<name>HelloSanDiego</name>
		<description>Simple overlay bitmap in San Diego</description>
		<GroundOverlay>
			<name>Simple overlay bitmap in San Diego</name>
			<LookAt>
				<longitude>-117.16818999089882</longitude>
				<latitude>32.71496098150528</latitude>
				<altitude>5.073048377858894</altitude>
				<heading>4.842019007966769E-10</heading>
				<tilt>0.0</tilt>
				<range>0.0</range>
				<altitudeMode>relativeToGround</altitudeMode>
			</LookAt>
			<Icon>
				<href>files/image.png</href>
			</Icon>
			<gx:LatLonQuad>
				<coordinates>-117.16818999089882,32.71496098150528,5.073048377858894 -117.1675446751236,32.71496097984488,5.073048377858894 -117.1675446751236,32.7155966911221,5.073048377858894 -117.16818999089882,32.715596692782505,5.073048377858894</coordinates>
			</gx:LatLonQuad>
		</GroundOverlay>
	</Document>
</kml>
```

**Comment by acespring78** [comment]
Hi, do we know if there are still plans to support `gx:LatLonQuad` in the near future?

**Comment by noberasco** [comment]
Old ticket, but it has revendly become relevant to one of our workflows, so I have raised a PR to fix this...
