### ISSUE TITLE
Clusters: Crash when zooming a lot

### ISSUE THREAD

**Issue by pascal-hauser** [googlemaps/android-maps-utils#651]
#### Environment details
Android Version 9
Library Version 1.0.0
Play Services Maps 17.0.0

#### Steps to reproduce
1. Zoom in and out a lot, so that the view changes between cluster and individual points.
2. App crashes with the stack trace below.

#### Stack trace
```
    java.lang.IllegalArgumentException: Unmanaged descriptor
        at com.google.maps.api.android.lib6.common.m.d(:com.google.android.gms.dynamite_mapsdynamite@200616081@20.06.16 (120400-0):0)
        at com.google.maps.api.android.lib6.impl.q.c(:com.google.android.gms.dynamite_mapsdynamite@200616081@20.06.16 (120400-0):3)
        at com.google.maps.api.android.lib6.impl.cy.a(:com.google.android.gms.dynamite_mapsdynamite@200616081@20.06.16 (120400-0):2)
        at com.google.maps.api.android.lib6.impl.cy.b(:com.google.android.gms.dynamite_mapsdynamite@200616081@20.06.16 (120400-0):1)
        at com.google.android.gms.maps.model.internal.o.a(:com.google.android.gms.dynamite_mapsdynamite@200616081@20.06.16 (120400-0):40)
        at ch.onTransact(:com.google.android.gms.dynamite_mapsdynamite@200616081@20.06.16 (120400-0):4)
        at android.os.Binder.transact(Binder.java:914)
        at com.google.android.gms.internal.maps.zza.zzb(Unknown Source:20)
        at com.google.android.gms.internal.maps.zzv.remove(Unknown Source:4)
        at com.google.android.gms.maps.model.Marker.remove(Unknown Source:4)
        at com.google.maps.android.collections.MarkerManager.removeObjectFromMap(MarkerManager.java:117)
        at com.google.maps.android.collections.MarkerManager.removeObjectFromMap(MarkerManager.java:32)
        at com.google.maps.android.collections.MapObjectManager$Collection.remove(MapObjectManager.java:110)
        at com.google.maps.android.collections.MapObjectManager.remove(MapObjectManager.java:91)
        at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.removeMarker(DefaultClusterRenderer.java:663)
        at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask(DefaultClusterRenderer.java:648)
        at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage(DefaultClusterRenderer.java:623)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by barbeau** [comment]
@pascal-hauser Are you able to reproduce this with the demo app in the project? If so, which demo for clustering are you using (e.g., Clustering, Clustering: Custom Look, Clustering: 2K markers, Clustering 20K Only Visible Markers, Clustering: ViewModel)?

**Comment by wangela** [comment]
Closing as stale; please reopen if this is still an issue.
