### ISSUE TITLE
App is crashing with Null pointer exception at line 789 of class com.google.maps.android.clustering.view.DefaultClusterRenderer.onClusterItemUpdated (DefaultClusterRenderer.java:789)

### ISSUE THREAD

**Issue by AnkurChitranshiBOL** [googlemaps/android-maps-utils#690]
After updating maps-utils:0.6.2 to maps-utils:1.02 My App is crashing on the zooming.

It is crashing while matching the Snippet value of Marker(which is null). 

**Environment details**

on ALL devices

**Steps to reproduce**
open the map and try to Zoom

**Stack trace**

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at com.google.maps.android.clustering.view.DefaultClusterRenderer.onClusterItemUpdated(DefaultClusterRenderer.java:789)
       at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.perform(DefaultClusterRenderer.java:973)
       at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.access$2000(DefaultClusterRenderer.java:934)
       at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask(DefaultClusterRenderer.java:650)
       at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage(DefaultClusterRenderer.java:621)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```
Thanks

**Comment by AnkurChitranshiBOL** [comment]
I have updated the version to 1.1.0 and not it is working fine.
