### ISSUE TITLE
Add GeoJsonLayer to map fails in maps SDK 3 beta 

### ISSUE THREAD

**Issue by ryust** [googlemaps/android-maps-utils#728]
I'm testing the maps SDK 3 beta along with the maps utils v3 (1.3.1). When adding a GeoJsonLayer to the map the app crashes with the following stacktrace. I don't know if it's a utils or maps v3 beta problem, but there appears to be more support here so I'll try here first.

 java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at com.google.android.libraries.maps.ct.zza.zza(GLAreaGroup.java:467)
        at com.google.android.libraries.maps.bl.zzk.<init>(ClientAreaImpl.java:98)
        at com.google.android.libraries.maps.bl.zzy.<init>(ClientAreaWorldSpaceImpl.java:1)
        at com.google.android.libraries.maps.bl.zze.zza(AreasImpl.java:100)
        at com.google.android.libraries.maps.ix.zzn.zza(FullyMutableClientArea.java:17)
        at com.google.android.libraries.maps.ix.zzav.zzh(PolygonRendererPhoenix.java:188)
        at com.google.android.libraries.maps.ix.zzav.zzc(PolygonRendererPhoenix.java:43)
        at com.google.android.libraries.maps.ix.zzat.zza(OverlayRendererManagerPhoenix.java:27)
        at com.google.android.libraries.maps.it.zzav.zza(GoogleMapImpl.java:441)
        at com.google.android.libraries.maps.GoogleMap.addPolygon(GoogleMap.java:29)
        at com.google.maps.android.collections.PolygonManager$Collection.addPolygon(PolygonManager.java:68)
        at com.google.maps.android.data.Renderer.addPolygonToMap(Renderer.java:939)
        at com.google.maps.android.data.Renderer.addMultiPolygonToMap(Renderer.java:1085)
        at com.google.maps.android.data.Renderer.addGeoJsonFeatureToMap(Renderer.java:762)
        at com.google.maps.android.data.Renderer.addFeature(Renderer.java:693)
        at com.google.maps.android.data.geojson.GeoJsonRenderer.addFeature(GeoJsonRenderer.java:84)
        at com.google.maps.android.data.geojson.GeoJsonRenderer.addLayerToMap(GeoJsonRenderer.java:73)
        at com.google.maps.android.data.Layer.addGeoJsonToMap(Layer.java:61)
        at com.google.maps.android.data.geojson.GeoJsonLayer.addLayerToMap(GeoJsonLayer.java:165)

**Comment by arriolac** [comment]
Will try to see if I can repro on the demo app using V3 Are you able to share the `.geojson` file that produces this crash?

**Comment by arriolac** [comment]
I was able to get the `GeoJsonDemoActivity` running on the V3 library just fine. Sharing the `.geojson` file that produces the crash should help us debug this.

**Comment by ryust** [comment]
I reverted back to v2 to stay away from the v3 beta. Everything was too slow with geojson overlays. I've attached one that caused problems on v3.

[Scotland.geojson.zip](https://github.com/googlemaps/android-maps-utils/files/4662507/Scotland.geojson.zip)

**Comment by a396901990** [comment]
same issue, happend after upgrade to v3

**Comment by wangela** [comment]
Closing since the v3 beta has been [deprecated](https://developers.google.com/maps/documentation/android-sdk/v310-beta).
