### ISSUE TITLE
java.lang.ClassCastException: com.google.maps.android.data.kml.KmlMultiGeometry cannot be cast to com.google.maps.android.data.kml.KmlPolygon

### ISSUE THREAD

**Issue by ForceGT** [googlemaps/android-maps-utils#769]
Basically I wrote a  function to extract data from the KmlLayer obtained from a URL (100% no issues with downloading that )
```
private fun extractDataFromKml(kmlLayer: KmlLayer?) {
            redZonePolygonMap = hashMapOf()
            **kmlLayer**!!.containers.forEach { container ->
                container.placemarks.forEach { placeMark ->


                    val polygon = placeMark.geometry as KmlPolygon
//                    polygon.geometryObject.forEach { pol->
//                        val name = placeMark.getProperty("name")
//                        val centerPoint = (pol as KmlPolygon).getApproximateCenter()
//                        val locationCoordinates = ArrayList<LatLng>()
//                        locationCoordinates.add(centerPoint)
//                        locationCoordinates.addAll(pol.outerBoundaryCoordinates)
//                        redZonePolygonMap!!.put(name, locationCoordinates)
//                    }


                    val name = placeMark.getProperty("name")
                    val centerPoint = (polygon as KmlPolygon).getApproximateCenter()
                    val locationCoordinates = ArrayList<LatLng>()
                    locationCoordinates.add(centerPoint)
                    locationCoordinates.addAll(polygon.outerBoundaryCoordinates)
                    redZonePolygonMap!!.put(name, locationCoordinates)

                    //Check if in Red Zone
//                            if (mLastLocation != null) {
//                                isInRedZone[name] = isInRedZone(
//                                    locationCoordinates, LatLng(
//                                        mLastLocation!!.latitude,
//                                        mLastLocation!!.longitude
//                                    )
//                                )
//                            }

                }

            }
```

*********************** ERROR CASE 1 ****************************************
```
java.lang.ClassCastException: com.google.maps.android.data.kml.KmlMultiGeometry cannot be cast to com.google.maps.android.data.kml.KmlPolygon
        at com.gtxtreme.pct.MapDetailFragment$DownloadKmlFile.extractDataFromKml(MapDetailFragment.kt:311)
        at com.gtxtreme.pct.MapDetailFragment$DownloadKmlFile.moveCameraToKml(MapDetailFragment.kt:303)
        at com.gtxtreme.pct.MapDetailFragment$DownloadKmlFile.addKmlToMap(MapDetailFragment.kt:288)
        at com.gtxtreme.pct.MapDetailFragment$DownloadKmlFile.onPostExecute(MapDetailFragment.kt:281)
        at com.gtxtreme.pct.MapDetailFragment$DownloadKmlFile.onPostExecute(MapDetailFragment.kt:239)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7398)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:919)

```

What I tried to fix it

An entire rewrite
```
private fun extractDataFromKml(kmlLayer: KmlLayer?) {
            redZonePolygonMap = hashMapOf()
            **kmlLayer**!!.containers.forEach { container ->
                container.placemarks.forEach { placeMark ->


                    val polygon = placeMark.geometry as KmlMutliGeometry
                    polygon.geometryObject.forEach { pol->
                        val name = placeMark.getProperty("name")
                        val centerPoint = (pol as KmlPolygon).getApproximateCenter()
                        val locationCoordinates = ArrayList<LatLng>()
                        locationCoordinates.add(centerPoint)
                        locationCoordinates.addAll(pol.outerBoundaryCoordinates)
                        redZonePolygonMap!!.put(name, locationCoordinates)
                    }


                    // val name = placeMark.getProperty("name")
                    // val centerPoint = (polygon as KmlPolygon).getApproximateCenter()
                    // val locationCoordinates = ArrayList<LatLng>()
                    // locationCoordinates.add(centerPoint)
                    // locationCoordinates.addAll(polygon.outerBoundaryCoordinates)
                    // redZonePolygonMap!!.put(name, locationCoordinates)

                    //Check if in Red Zone
//                            if (mLastLocation != null) {
//                                isInRedZone[name] = isInRedZone(
//                                    locationCoordinates, LatLng(
//                                        mLastLocation!!.latitude,
//                                        mLastLocation!!.longitude
//                                    )
//                                )
//                            }

                }

            }
```

****************** ERROR CASE 2 ****************
It's just the reverse (Hell yeah)

```
java.lang.ClassCastException: com.google.maps.android.data.kml.KmlPolygon cannot be cast to com.google.maps.android.data.kml.KmlMultiGeometry
        at com.gtxtreme.pct.MapDetailFragment$DownloadKmlFile.extractDataFromKml(MapDetailFragment.kt:311)
        at com.gtxtreme.pct.MapDetailFragment$DownloadKmlFile.moveCameraToKml(MapDetailFragment.kt:303)
        at com.gtxtreme.pct.MapDetailFragment$DownloadKmlFile.addKmlToMap(MapDetailFragment.kt:288)
        at com.gtxtreme.pct.MapDetailFragment$DownloadKmlFile.onPostExecute(MapDetailFragment.kt:281)
        at com.gtxtreme.pct.MapDetailFragment$DownloadKmlFile.onPostExecute(MapDetailFragment.kt:239)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7398)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:919)
```

On trying to check the value of variable **kmlLayer**

Here is a general structure (Since I couldn't copy 1007 placemarks) : [Imgur](https://imgur.com/a/8n4kZhT)

** Reference taken from official demo app**
[Here](https://github.com/googlemaps/android-maps-utils/blob/master/demo/src/main/java/com/google/maps/android/utils/demo/KmlDemoActivity.java)

**Comment by arriolac** [comment]
Looks like each `KMLPlacemark` has a different geometry type. You can use the `when` statement to handle different geometry types:

```
        kmlLayer.containers.forEach { container -> {
            container.placemarks.forEach { placemark ->
                when (placemark.geometry) {
                    is KmlPolygon -> {
                        // Handle KmlPolygon case
                    }
                    is KmlMultiGeometry -> {
                        // Handle KmlMultiGeometry case
                    }
                    else -> {
                        // Handle other geometry case
                    }
                }
            }
        }}
```

**Comment by ForceGT** [comment]
> Looks like each `KMLPlacemark` has a different geometry type. You can use the `when` statement to handle different geometry types:
> 
> ```
>         kmlLayer.containers.forEach { container -> {
>             container.placemarks.forEach { placemark ->
>                 when (placemark.geometry) {
>                     is KmlPolygon -> {
>                         // Handle KmlPolygon case
>                     }
>                     is KmlMultiGeometry -> {
>                         // Handle KmlMultiGeometry case
>                     }
>                     else -> {
>                         // Handle other geometry case
>                     }
>                 }
>             }
>         }}
> ```

Hey Man Thanks for saving my a** . Was so much worked up for almost a couple of days

**Comment by arriolac** [comment]
No problem! Glad that resolved your issue.
