### ISSUE TITLE
Release build of app throws java.lang.NoClassDefFoundError when trying to load map

### ISSUE THREAD

**Issue by lmj0011** [googlemaps/android-maps-utils#787]
#### Summary

Map crashes instantly when trying to load, seems to only happen in signed release build. Everything works as expected
in the debug build. Verified API Keys are valid.

#### Expected behavior
Map to load 

#### Observed behavior
Crash

#### Environment details

1. Device make and model, or emulator details
Pixel XL

2. Android version
Android 10 

3. Library version and other environment information
Using BETA utils with Maps SDK V3.0.0 BETA

```
implementation 'com.android.support:support-v4:+'
implementation 'com.android.support:appcompat-v7:+'
implementation 'com.google.android.gms:play-services-basement:17.2.1'
implementation 'com.google.android.gms:play-services-base:17.2.1'
implementation 'com.google.android.gms:play-services-gcm:17.0.0'
implementation 'com.google.android.gms:play-services-location:17.0.0'

implementation 'com.google.maps.android:android-maps-utils-sdk-v3-compat:0.1'
```

#### Steps to reproduce
- enable [coreLibraryDesugaring](https://developer.android.com/studio/write/java8-support?utm_source=android-studio-4-0&utm_medium=studio-assistant-stable#library-desugaring) in `app/build.gradle`

- build release apk

- open app and navigate to where a Google map is suppose to load

#### Code example

https://github.com/lmj0011/courier-locker/blob/92b2ca77c9ce290088c8b2ffb92684f8f852f9ad/app/build.gradle#L85-L90

#### Stack trace
```
Fatal Exception: java.lang.NoClassDefFoundError: tname=TilePrepPool2 - Failed resolution of: Lj$/util/SortedSet;
       at com.google.android.libraries.maps.fm.zzj.<init>(zzj.java:2)
       at com.google.android.libraries.maps.dk.zza.zzay(zza.java:8)
       at com.google.android.libraries.maps.dk.zza.zzx(zza.java:27)
       at com.google.android.libraries.maps.gu.zzat.zza(zzat.java:27)
       at com.google.android.libraries.maps.it.zzav.zza(zzav.java:11)
       at com.google.android.libraries.maps.it.zzci.zza(zzci.java:11)
       at com.google.android.libraries.maps.it.zzcg.zza(zzcg.java:11)
       at com.google.android.libraries.maps.SupportMapFragment$zza.onCreateView(SupportMapFragment.java:5)
       at com.google.android.gms.dynamic.zac.zaa(zac.java:5)
       at com.google.android.gms.dynamic.DeferredLifecycleHelper.zaa(DeferredLifecycleHelper.java:4)
       at com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreateView(DeferredLifecycleHelper.java:1)
       at com.google.android.libraries.maps.SupportMapFragment.onCreateView(SupportMapFragment.java:1)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:15)
       at androidx.fragment.app.FragmentStateManager.ensureInflatedView(FragmentStateManager.java:29)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:29)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:3)
       at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:3)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:239)
       at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
       at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:14)
       at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:2)
       at name.lmj0011.courierlocker.fragments.EditAptBuildingsMapsFragment.onCreateView(EditAptBuildingsMapsFragment.java:20)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:15)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:33)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:33)
       at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:37)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:8)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:94)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:4)
       at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:3)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by lmj0011** [comment]
Turns out Java 8+ API [desugaring support](https://developer.android.com/studio/write/java8-support?utm_source=android-studio-4-0&utm_medium=studio-assistant-stable#library-desugaring), is causing this crash somehow. I believe it's linked to the separate DEX file that it produces for [whatever reason](https://jakewharton.com/d8-library-desugaring/#second-dex).

> To support these language APIs, the plugin compiles a separate DEX file that contains an implementation of the missing APIs and includes it in your app. The desugaring process rewrites your app’s code to instead use this library at runtime.

The best workaround I could find was to remove desugaring, which eliminated the second `classes.dex` file, which then let the map load like normal.

**Comment by lmj0011** [comment]
Turns out Java 8+ API [desugaring support](https://developer.android.com/studio/write/java8-support?utm_source=android-studio-4-0&utm_medium=studio-assistant-stable#library-desugaring), is causing this crash somehow. I believe it's linked to the separate DEX file that it produces for [whatever reason](https://jakewharton.com/d8-library-desugaring/#second-dex).

> To support these language APIs, the plugin compiles a separate DEX file that contains an implementation of the missing APIs and includes it in your app. The desugaring process rewrites your app’s code to instead use this library at runtime.

The best workaround I could find was to remove desugaring, which eliminated the extra `classes.dex` file, and then let the map load like normal.

**Comment by wangela** [comment]
Closing since the v3 beta is [deprecated](https://developers.google.com/maps/documentation/android-sdk/v310-beta).
