### ISSUE TITLE
UninitializedPropertyAccessException: lateinit property clusterManager has not been initialized

### ISSUE THREAD

**Issue by ummerakbar** [googlemaps/android-maps-utils#807]
```
2020-12-03 19:09:52.382 23492-23492/com.xxx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxx, PID: 23492
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx/com.dashboard.HomeActivity}: kotlin.UninitializedPropertyAccessException: lateinit property clusterManager has not been initialized
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2861)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property clusterManager has not been initialized
        at com.xxx.dashboard.HomeActivity.access$getClusterManager$p(HomeActivity.kt:44)
        at com.xxx.dashboard.HomeActivity$observerPropData$1.onChanged(HomeActivity.kt:388)
        at com.xxx.dashboard.HomeActivity$observerPropData$1.onChanged(HomeActivity.kt:44)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:468)
        at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:144)
        at androidx.lifecycle.ReportFragment.onStart(ReportFragment.java:109)
        at android.app.Fragment.performStart(Fragment.java:2534)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1315)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1618)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3027)
        at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2984)
        at android.app.FragmentController.dispatchStart(FragmentController.java:189)
        at android.app.Activity.performStart(Activity.java:7058)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2824)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6626) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

#### Summary
some times App from background crashes with above exception

#### Observed behavior
First time App works fine but sometimes it throws exception-
`in oncreate method
  // Obtain the SupportMapFragment and get notified when the map is ready to be used.
        val mapFragment = supportFragmentManager
                .findFragmentById(R.id.map) as SupportMapFragment
        mapFragment.getMapAsync(this)`
`  */
    override fun onMapReady(googleMap: GoogleMap) {

        mMap = googleMap
        mMap.setOnCameraMoveStartedListener(this)
        // Initialize the manager with the context and the map.
        clusterManager = ClusterManager(this, mMap)`

#### Environment details

Android 8-9

**Comment by dkati** [comment]
Please clean up your post with <code> tags fixed. cant really understand what you say

**Comment by barbeau** [comment]
@ummerakbar Thanks for the report. Are you able to reproduce this in a small demo app on GitHub? It would help us troubleshoot.

From the above stack trace, I'm guessing that you have LiveData set up that's triggering an access `clusterManager` before the callback to `onMapReady()` happens and `clusterManager` is initialized. Possible workaround for this would be to remove the `lateinit` modifier from `clusterManager` and do a null check before using it, or don't allow the LiveData callbacks to happen until after the `clusterManager` is initialized.

**Comment by kikoso** [comment]
@ummerakbar , can you let us know ifthe suggestion from @barbeau works out? Thanks!
