### ISSUE TITLE
Crashes on release build of app but works fine on debug requireNonNull

### ISSUE THREAD

**Issue by darbysauter** [googlemaps/android-maps-utils#809]
#### Summary

Loading the map works fine on debug build but not release

#### Expected behavior

No crash

#### Observed behavior

Crash when loading map

#### Environment details

1. Pixel 3 Android 11
2. Compiled on SDK 29
3. com.google.android.libraries.maps:maps:3.1.0-beta
4. com.google.maps.android:android-maps-utils-v3:2.2.0

#### Steps to reproduce

  1. Not too sure how to reproduce without posting project

#### Code example

Not exactly sure what code is causing this, as it only happens on release build and none of my code is contained in the stack trace, I can confirm using logs that it occurs after all of my code in onMapReady()

#### Stack trace
```
2020-12-30 13:15:34.273 4274-4504/? E/AndroidRuntime: FATAL EXCEPTION: DefaultPool6
    Process: com.myapp, PID: 4274
    java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:220)
        at com.google.android.libraries.maps.lv.zzj.<init>(Unknown Source:3)
        at com.google.android.libraries.maps.lv.zzau.zza(Unknown Source:19)
        at com.google.android.libraries.maps.lv.zze.zzb(:1)
        at com.google.android.libraries.maps.lv.zze.zza(Unknown Source:2)
        at com.google.android.libraries.maps.eq.zzo.zza(Unknown Source:28)
        at com.google.android.libraries.maps.eq.zzc.zza(Unknown Source:11)
        at com.google.android.libraries.maps.fj.zzi.zza(Unknown Source:28)
        at com.google.android.libraries.maps.fj.zzi.zza(Unknown Source:81)
        at com.google.android.libraries.maps.fj.zzd.run(Unknown Source:6)
        at com.google.android.libraries.maps.fv.zzc.run(Unknown Source:4)
        at com.google.android.libraries.maps.fv.zzae.run(Unknown Source:7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.libraries.maps.fv.zzv.run(Unknown Source:50)
        at java.lang.Thread.run(Thread.java:923)
```

EDIT: I've been trying many different things and found disabling minification on the release build makes it build fine. I am not sure how to properly figure this out though.

EDIT 2: Here are logs of when the app has minify enabled and crashes vs minify disabled

```
2020-12-30 16:07:41.967 19881-19937/? I/GenericGraph: Done Recent datasetEntries: 3 testPoints: 3 sizeDif: 0 took: 1 MS
2020-12-30 16:07:42.220 19881-19881/? I/zzaw: Making Creator statically
2020-12-30 16:07:42.226 19881-19881/? I/Google Maps SDK for Android: Google Play services client version: 12451000
2020-12-30 16:07:42.228 19881-19881/? I/Google Maps SDK for Android: Google Play services package version: 204516046
2020-12-30 16:07:42.448 19881-20028/? W/Glide: Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
2020-12-30 16:07:42.457 19881-20028/? I/TetheringManager: registerTetheringEventCallback:com.myapp
2020-12-30 16:07:42.481 19881-19881/? E/libEGL: eglQueryContextImpl:1112 error 3006 (EGL_BAD_CONTEXT)
2020-12-30 16:07:42.490 19881-19881/? E/ThemeUtils: View class com.google.maps.android.ui.SquareTextView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2020-12-30 16:07:42.492 19881-19881/? E/ThemeUtils: View class com.google.maps.android.ui.SquareTextView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2020-12-30 16:07:42.606 19881-20037/? W/Gralloc4: allocator 3.x is not supported
2020-12-30 16:07:42.606 19881-20037/? W/Gralloc3: allocator 3.x is not supported


2020-12-30 16:07:42.877 19881-19891/? I/. com.myapp: Compiler allocated 8144KB to compile 
    void 
        com.google.android.libraries.maps.df.zzr.zza(
            com.google.android.libraries.maps.cf.zzbr, 
            com.google.android.libraries.maps.cf.zzbi, 
            com.google.android.libraries.maps.du.zzb, 
            com.google.android.libraries.maps.ek.zzf, 
            android.content.res.Resources, 
            com.google.android.libraries.maps.cf.zzab)

2020-12-30 16:07:43.012 19881-19891/? I/. com.myapp: Compiler allocated 9105KB to compile 
    void 
        com.google.android.libraries.maps.df.zzr.zza(
            com.google.android.libraries.maps.cf.zzbr, 
            com.google.android.libraries.maps.cf.zzbi, 
            com.google.android.libraries.maps.du.zzb, 
            com.google.android.libraries.maps.ek.zzf, 
            android.content.res.Resources, 
            com.google.android.libraries.maps.cf.zzab)

2020-12-30 16:07:43.244 19881-19891/? I/. com.myapp: Compiler allocated 5215KB to compile 
    com.google.android.libraries.maps.cf.zzbr 
        com.google.android.libraries.maps.cf.zzbr.zza(
            com.google.android.libraries.maps.ds.zzf$zzb, 
            com.google.android.apps.gmm.map.api.model.zzak, 
            com.google.android.libraries.maps.cf.zzbl, 
            com.google.android.libraries.maps.lc.zzt, 
            com.google.android.libraries.maps.cf.zzbk, 
            com.google.android.libraries.maps.cf.zzt, 
            com.google.android.apps.gmm.map.api.model.zzal, 
            int)


2020-12-30 16:07:44.475 19881-20045/? W/DynamiteModule: Local module descriptor class for com.google.android.gms.googlecertificates not found.
2020-12-30 16:07:44.488 19881-20045/? I/DynamiteModule: Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:6
2020-12-30 16:07:44.489 19881-20045/? I/DynamiteModule: Selected remote version of com.google.android.gms.googlecertificates, version >= 6
2020-12-30 16:07:44.489 19881-20045/? V/DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
2020-12-30 16:07:44.507 19881-20045/? I/DynamiteLoaderV2Impl: [71] Googlecertificates
2020-12-30 16:08:02.471 1152-3121/? D/NuPlayerDriver: NuPlayerDriver(0xee1032b0) created, clientPid(19881)
```

```
2020-12-30 16:10:01.658 20362-20447/? I/a: Done Recent datasetEntries: 2 testPoints: 2 sizeDif: 0 took: 0 MS
2020-12-30 16:10:02.038 20362-20362/? I/zzaw: Making Creator statically
2020-12-30 16:10:02.044 20362-20362/? I/Google Maps SDK for Android: Google Play services client version: 12451000
2020-12-30 16:10:02.045 20362-20362/? I/Google Maps SDK for Android: Google Play services package version: 204516046
2020-12-30 16:10:02.278 20362-20579/? W/Glide: Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
2020-12-30 16:10:02.286 20362-20579/? I/TetheringManager: registerTetheringEventCallback:com. com.myapp
2020-12-30 16:10:02.308 20362-20362/? E/libEGL: eglQueryContextImpl:1112 error 3006 (EGL_BAD_CONTEXT)
2020-12-30 16:10:02.317 20362-20362/? E/ThemeUtils: View class com.google.maps.android.ui.SquareTextView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2020-12-30 16:10:02.319 20362-20362/? E/ThemeUtils: View class com.google.maps.android.ui.SquareTextView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2020-12-30 16:10:02.431 20362-20585/? W/Gralloc4: allocator 3.x is not supported
2020-12-30 16:10:02.432 20362-20585/? W/Gralloc3: allocator 3.x is not supported


2020-12-30 16:10:02.494 20362-20372/? I/.myapp: Compiler allocated 8201KB to compile 
    void 
        com.google.android.libraries.maps.df.zzr.zza(
            com.google.android.libraries.maps.cf.zzbr, 
            com.google.android.libraries.maps.cf.zzbi, 
            com.google.android.libraries.maps.du.zzb, 
            com.google.android.libraries.maps.ek.zzf, 
            android.content.res.Resources, 
            com.google.android.libraries.maps.cf.zzab)

2020-12-30 16:10:02.603 20362-20372/? I/.myapp: Compiler allocated 9095KB to compile 
    void 
        com.google.android.libraries.maps.df.zzr.zza(
            com.google.android.libraries.maps.cf.zzbr, 
            com.google.android.libraries.maps.cf.zzbi, 
            com.google.android.libraries.maps.du.zzb, 
            com.google.android.libraries.maps.ek.zzf, 
            android.content.res.Resources, 
            com.google.android.libraries.maps.cf.zzab)

2020-12-30 16:10:02.733 20362-20372/? I/.myapp: Compiler allocated 4343KB to compile 
    boolean 
        com.google.android.libraries.maps.ct.zzcn.zza(
            com.google.android.libraries.maps.bm.zzu, 
            com.google.android.libraries.maps.ct.zzcj, 
            com.google.android.libraries.maps.cw.zzd, 
            com.google.android.libraries.maps.cf.zzad, 
            com.google.android.libraries.maps.ct.zzco, 
            com.google.android.libraries.maps.bj.zzak)

2020-12-30 16:10:02.782 20362-20372/? I/.myapp: Compiler allocated 6262KB to compile 
    com.google.android.libraries.maps.cf.zzbr 
        com.google.android.libraries.maps.cf.zzbr.zza(
            com.google.android.libraries.maps.ds.zzf$zzb, 
            com.google.android.apps.gmm.map.api.model.zzak, 
            com.google.android.libraries.maps.cf.zzbl, 
            com.google.android.libraries.maps.lc.zzt, 
            com.google.android.libraries.maps.cf.zzbk, 
            com.google.android.libraries.maps.cf.zzt, 
            com.google.android.apps.gmm.map.api.model.zzal, 
            int)

2020-12-30 16:10:02.811 20362-20372/? I/.myapp: Compiler allocated 4448KB to compile 
    boolean 
        com.google.android.libraries.maps.ct.zzcn.zza(
            com.google.android.libraries.maps.bm.zzu, 
            com.google.android.libraries.maps.ct.zzcj, 
            com.google.android.libraries.maps.cw.zzd, 
            com.google.android.libraries.maps.cf.zzad, 
            com.google.android.libraries.maps.ct.zzco, 
            com.google.android.libraries.maps.bj.zzak)


2020-12-30 16:10:03.304 20362-20362/? D/AndroidRuntime: Shutting down VM
2020-12-30 16:10:03.305 20362-20362/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp, PID: 20362
    java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:220)
        at com.google.android.libraries.maps.lv.zzj.<init>(Unknown Source:3)
        at com.google.android.libraries.maps.lv.zzau.zza(Unknown Source:19)
        at com.google.android.libraries.maps.lv.zze.zzb(:1)
        at com.google.android.libraries.maps.lv.zze.zza(Unknown Source:2)
        at com.google.android.libraries.maps.eq.zzo.zza(Unknown Source:28)
        at com.google.android.libraries.maps.eq.zzc.zza(Unknown Source:11)
        at com.google.android.libraries.maps.fj.zzi.zza(Unknown Source:28)
        at com.google.android.libraries.maps.fj.zzi.zza(Unknown Source:81)
        at com.google.android.libraries.maps.fj.zzd.run(Unknown Source:6)
        at com.google.android.libraries.maps.fv.zzc.run(Unknown Source:4)
        at com.google.android.libraries.maps.fv.zzae.run(Unknown Source:7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.libraries.maps.fv.zzv.run(Unknown Source:50)
        at java.lang.Thread.run(Thread.java:923)
2020-12-30 16:10:03.338 20362-20362/? I/Process: Sending signal. PID: 20362 SIG: 9

```

**Comment by barbeau** [comment]
@darbysauter You usually see these kinds of errors when the minification tool (now R8, previously Proguard) strips out classes, fields, or methods that are needed at runtime. I haven't seen this particular issue before, though, with Maps SDK v3 beta. The fix is to find the right minification configuration in your `proguard-rules.pro` file to keep the things needed at runtime.

There are some configuration suggestions here you can try:
https://stackoverflow.com/questions/57674484/proguard-rules-for-maps-v3-0-0-beta

I'll see if I can take a look as well.

**Comment by barbeau** [comment]
I've created a product flavor `v3` of the demo app here that hopefully we can use to reproduce this:
https://github.com/googlemaps/android-maps-utils/pull/811

**Comment by barbeau** [comment]
I can confirm that I can reproduce this with a signed release of `v3Release` variant in #811. 

When `minifyEnabled false` I can start the various activities from the main screen without any problems (with the exception of "SphericalUtil.ComputedDistanceBetween" - but I think that's a separate issue that I will open). 

However, with `minifyEnabled true` all of the activities briefly show on the screen and then crash. Here's the error I'm seeing in LogCat when that happens:

~~~
2021-01-06 15:50:20.560 8596-8651/? E/AndroidRuntime: FATAL EXCEPTION: DefaultPool7
    Process: com.google.maps.android.utils.demo.v3, PID: 8596
    java.lang.NullPointerException: throw with null exception
        at com.google.android.libraries.maps.lv.zzj.<init>(Unknown Source:9)
        at com.google.android.libraries.maps.lv.zzau.zza(Unknown Source:19)
        at com.google.android.libraries.maps.lv.zze.zzb(:1)
        at com.google.android.libraries.maps.lv.zze.zza(Unknown Source:2)
        at com.google.android.libraries.maps.eq.zzo.zza(Unknown Source:28)
        at com.google.android.libraries.maps.eq.zzc.zza(Unknown Source:11)
        at com.google.android.libraries.maps.fj.zzi.zza(Unknown Source:30)
        at com.google.android.libraries.maps.fj.zzi.zza(Unknown Source:85)
        at com.google.android.libraries.maps.fj.zzd.run(Unknown Source:8)
        at com.google.android.libraries.maps.fv.zzc.run(Unknown Source:4)
        at com.google.android.libraries.maps.fv.zzae.run(Unknown Source:7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.libraries.maps.fv.zzv.run(Unknown Source:50)
        at java.lang.Thread.run(Thread.java:764)
~~~

**Comment by darbysauter** [comment]
That stacktrace looks to be exactly what I am getting.

@barbeau  Thanks for taking a look into this

I resolved this thanks to someone on the Android Dev discord.
They mentioned this issue: https://issuetracker.google.com/issues/148084488
and this fix:
```
-keep,allowoptimization class com.google.android.libraries.maps.** { *; }
```
(Which was also on the stackoverflow post you sent)

Which fixed my issue. Should work fine until this is fixed in the next beta release hopefully

**Comment by barbeau** [comment]
@darbysauter Thanks for finding the issue and fix! I'll add this to the proguard config in #811 for the v3 variant there.

Seems this is definitely an issue in the Maps SDK v3 beta then, and not AMU library, so I'm going to close out this issue. If you have any other issues/questions please comment or re-open.
