### ISSUE TITLE
app crash during migration

### ISSUE THREAD

**Issue by danilshik** [googlemaps/android-maps-utils#844]
#### Summary

Since google decided not to fix the map bug on the old sdks and recommended switching to the new sdk, I tried switching, but my map crashes
#### Expected behavior

Working map with clustering

#### Observed behavior

App crashes when opening the map

#### Environment details

1. Xiaomi Redmi 7 (MIUI 11.0.5.0)
2. Android 9
3. Since the library version 2.2.1 and 2.2.2 were not available during the build, we had to stop at 2.2.0
implementation 'com.google.maps.android:android-maps-utils-v3:2.2.0'
implementation 'com.google.android.libraries.maps:maps:3.1.0-beta'

#### Code example
Unfortunately, I'm migrating from the old library to the new one and can't be sure if this is a problem of new maps or new utils, and the log doesn't give a clue of this, so I'll have to lay out all the code of this class
```
class MapNewTwoFragment: BaseFragment(), OnMapReadyCallback, OnClusterClickListener<DotX>,
        OnClusterItemClickListener<DotX>, LocationListener {
    lateinit var toolbar: androidx.appcompat.widget.Toolbar
    lateinit var toolbarTitle : TextView
    lateinit var imageViewBack : ImageView
    lateinit var fab : FloatingActionButton
    lateinit var mainActivity: MainActivity
    private var renderer: DotRenderer? = null
    private var googleMap: GoogleMap? = null
    private var COUNT_POINT_FOR_RENDER_IN_CLUSTER = 1
    lateinit var viewModel: MapNewTwoViewModel
    private var clusterManager : ClusterManager<DotX>? = null
    private val POLYLINE_STROKE_WIDTH_PX = 2
    private var allOrders = HashMap<String, OrderX>()
    private var allPolylines = HashMap<String, Polyline>()
    private var markersSingleOrder = mutableListOf<Marker>()


    /**
     * Храним последнии координаты точки
     */
    private var allDots = HashMap<String, DotXPosition>()
    /**
     * Для очистки
     */
    private var courierMarker: Marker? = null
    // Permission
    private val ACCESS_FINE_LOCATION = 10
    private val ACCESS_COARSE_LOCATION = 20
    private var provider: String? = null
    private var locationManager: LocationManager? = null
    private var location: Location? = null

    private var isSingleMode = false

    override fun onCreateView(
            inflater: LayoutInflater,
            container: ViewGroup?,
            savedInstanceState: Bundle?
    ): View? {

        return inflater.inflate(R.layout.fragment_map_new, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        Log.d("MapNewTwoFragment", "onViewCreated")

        checkPermissionsStart()

        toolbar = view.findViewById(R.id.toolbar)
        toolbar.visibility = View.GONE
        toolbarTitle = view.findViewById(R.id.toolbar_title)
        imageViewBack = view.findViewById(R.id.imageView_back)
        imageViewBack.setOnClickListener {
            onBackPressedNew()
        }

        fab = view.findViewById(R.id.fab)
        context?.let {
            fab.backgroundTintList =
                ContextCompat.getColorStateList(requireContext(), R.color.colorTextWhite)
        }
        fab.setOnClickListener { showBottomSheetOrders() }

        val application = requireNotNull(this.activity).application
        val netManager = NetManager(application)
        val database = AppDatabase.getDatabase(application).settingsDao()
        val repository =
            RepositoryOrder(netManager, database)
        val viewModelFactory = MapNewTwoViewModelFactory(repository, application)

        viewModel = ViewModelProvider(requireActivity(), viewModelFactory).get(MapNewTwoViewModel::class.java)
    }

    override fun onResume() {
        super.onResume()
        setupMap()
        Log.d("MapNewTwoFragment", "onResume")
//        clearAll()
        viewModel.loadAll()
    }

    private fun setupCluster(map: GoogleMap) {
        clusterManager = ClusterManager(MyApplication.applicationContext(), map)
        renderer = DotRenderer()
        clusterManager?.renderer = renderer
        clusterManager?.algorithm = CustomScreenBasedAlgorithmAdapter(PreCachingAlgorithmDecorator(NonHierarchicalDistanceBasedAlgorithm()))
        map.setOnCameraIdleListener(clusterManager)
//        map.setOnMarkerClickListener(clusterManager)
//        map.setOnInfoWindowClickListener(clusterManager)
        clusterManager?.setOnClusterClickListener(this)
        clusterManager?.setOnClusterItemClickListener(this)
    }
    private fun setItemsCluster(orders: List<OrderX>){
        clearAll()
        /**
         * Очищаем все
         */
        val itemClusters = mutableListOf<DotX>()
        for (order in orders) {
            itemClusters.addAll(order.dots)
            allOrders[order.id.toString()] = order
            for (dot in order.dots) {
                allDots[dot.id] = DotXPosition(dot, dot.position, false)
            }
        }
        clusterManager?.addItems(itemClusters)
        clusterManager?.cluster()


        /**
         * Показ курьера для заказчика (показывает только для 1 заказа), не подчинается кластеризации
         */
        if(mainActivity.settings.type == "2")
            if(orders.size == 1) {
                if(orders[0].courier.coordinates != null){
                    val latLng = LatLng(
                            orders[0].courier.coordinates!!.lat, orders[0].courier.coordinates!!.lng
                    )
                    val marker = MarkerOptions()
                            .position(latLng)
                            .icon(getCourierItem())
                            .title("Курьер")
                    courierMarker = googleMap?.addMarker(marker)
                }
            }


    }

    private fun setupViewModel(){
        var dialog : MaterialDialog? = null
        viewModel.observeState(this) {
            when(it){
                is MapNewTwoState.Loading -> {
                    context?.let {
                        dialog = MDialog(context, viewLifecycleOwner).show {
                            title(text = "Получение данных")
                            message(text = "Получение списка заказов. Пожалуйста, подождите...")

                        }
                    }
                }
                is MapNewTwoState.MyOrders -> {
                    dialog?.dismiss()
                }
                is MapNewTwoState.AvailableOrders -> {
                    dialog?.dismiss()
                }
                is MapNewTwoState.AllOrders -> {
                    dialog?.dismiss()
                }
                else -> {

                }
            }
        }
        viewModel.observeNotifications(this) {
            when(it){
                is Notify.TextMessage -> {
                    Toast.makeText(context, it.message, Toast.LENGTH_LONG).show()
                }
                is Notify.ActionMessage -> {
                    Toast.makeText(context, it.message, Toast.LENGTH_LONG).show()
                    it.actionHandler.invoke()
                }

                else -> {}
            }
        }
        viewModel.mediatorLiveData.observe(viewLifecycleOwner, {
            Log.d("MediatorLiveData size", it.size.toString())
            if (viewModel.isSingleOrders)
                COUNT_POINT_FOR_RENDER_IN_CLUSTER = Int.MAX_VALUE
            else
                COUNT_POINT_FOR_RENDER_IN_CLUSTER = 1
            setItemsCluster(it)
        })
    }

    private fun clearMarkers(){
        Log.d("Clear MarkersSigngle Before", allPolylines.size.toString())
        markersSingleOrder.forEach {
            it.remove()
        }
        markersSingleOrder.clear()
        Log.d("Clear MarkersSigngle Before", allPolylines.size.toString())
    }


    private fun clearAll(){
        clearAllPolylines()
        clearMarkers()
        allDots.clear()
        allOrders.clear()
        clusterManager?.clearItems()
        courierMarker?.remove()
        clusterManager?.cluster()
    }



    private fun setupMap(){
        val fragment = childFragmentManager.findFragmentById(R.id.googleMap) as SupportMapFragment
        fragment.getMapAsync(this)

    }


    private fun getBundle(){
        val bundle = this.arguments
        if(bundle != null){
            val orderString = bundle.getString("order")
            val order = Gson().fromJson(orderString, OrderX::class.java)
            Log.d("Fragment isClient", bundle.getBoolean("isClient", false).toString())
            viewModel.setTypeUser(bundle.getBoolean("isClient", false))
            if(order != null){
                viewModel.isSingleOrders = true
                Log.d("Bundle isMyOrder", bundle.getInt("myOrder").toString())
                if(bundle.getInt("myOrder") == 1){
                    toolbar.visibility = View.VISIBLE
                    toolbarTitle.text = "Заказ №${order!!.id}"
                    Log.d("MyBundle", true.toString())
                    viewModel.setType(
                            MapNewTwoViewModel.OrderType.SingleOrder(), listOf(
                            order.copy(
                                    isMyOrder = true
                            )
                    )
                    )
                } else if(bundle.getInt("myOrder") == 0){
                    Log.d("MyBundle", false.toString())
                    viewModel.setType(
                            MapNewTwoViewModel.OrderType.SingleOrder(), listOf(
                            order.copy(
                                    isMyOrder = false
                            )
                    )
                    )
                }
                if(order.dots.isNotEmpty()) {
                    val coordinates = order.dots[0].coordinates
                    moveCamera(LatLng(coordinates.lat, coordinates.lng), 10f)
                }
            }
//            else{
//                viewModel.setType(MapNewTwoViewModel.OrderType.AllOrders())
//            }
        }
//        else{
//            viewModel.setType(MapNewTwoViewModel.OrderType.AllOrders())
//        }
    }

    private fun onBackPressedNew() {
        val fm: FragmentManager = mainActivity.supportFragmentManager
        if (fm.backStackEntryCount > 0) {
            fm.popBackStack()
        }
    }

    override fun onMapReady(map: GoogleMap?) {
        Log.d("MapNewTwoFragment", "onMapReady")
        googleMap = map
        googleMap?.uiSettings?.isMyLocationButtonEnabled = true
        googleMap?.uiSettings?.isZoomControlsEnabled = true
        googleMap?.uiSettings?.isCompassEnabled = true
        googleMap?.let {
            setupCluster(googleMap!!)
        }
        googleMap?.setOnMapClickListener {
            if (viewModel.isClient) {
                viewModel.setType(MapNewTwoViewModel.OrderType.MyOrders())
            } else
                viewModel.setType(MapNewTwoViewModel.OrderType.AllOrders())

        }
        locationManager = mainActivity.getSystemService(Context.LOCATION_SERVICE) as LocationManager
        val criteria = Criteria()
        provider = locationManager!!.getBestProvider(criteria, true)
        if (provider != null) {
            checkPermissions()
        }

        val permissions = arrayOf(
                Manifest.permission.ACCESS_FINE_LOCATION,
                Manifest.permission.ACCESS_COARSE_LOCATION
        )
        val rationale = "Приложению необходим доступ к геолокации"
        val options = Permissions.Options()
                .setRationaleDialogTitle("Информация")
                .setSettingsDialogTitle("Предупреждение")

        Permissions.check(
                mainActivity,
                permissions,
                rationale,
                options,
                object : PermissionHandler() {
                    override fun onGranted() {
                        checkPermissions()
                    }

                    override fun onDenied(context: Context, deniedPermissions: ArrayList<String>) {
                        // permission denied, block the feature.
                    }
                })

        googleMap?.setOnMyLocationButtonClickListener {
            try {
                when {
                    location != null -> {
                        moveCamera(
                                LatLng(
                                        location!!.latitude,
                                        location!!.longitude
                                ), 13f
                        )
                        return@setOnMyLocationButtonClickListener false
                    }
                    mainActivity.settings.latitude != "" -> {
                        moveCamera(
                                LatLng(
                                        mainActivity.settings.latitude.toDouble(),
                                        mainActivity.settings.longitude.toDouble()
                                ), 13f
                        )

                        return@setOnMyLocationButtonClickListener false
                    }
                    else -> {
                        return@setOnMyLocationButtonClickListener false
                    }
                }
            } catch (e: Exception) {
                e.printStackTrace()
            }

            true
        }

        when {
            location != null -> moveCamera(
                    LatLng(
                            location!!.latitude,
                            location!!.longitude
                    ), 9f
            )
            mainActivity.settings.latitude != "" -> moveCamera(
                    LatLng(
                            mainActivity.settings.latitude.toDouble(),
                            mainActivity.settings.longitude.toDouble()
                    ), 9f
            )
        }
        getBundle()
        setupViewModel()
    }

    private fun checkPermissions() {
        try {
            if (ActivityCompat.checkSelfPermission(
                            mainActivity,
                            Manifest.permission.ACCESS_FINE_LOCATION
                    ) != PackageManager.PERMISSION_GRANTED
            ) {
                ActivityCompat.requestPermissions(
                        mainActivity,
                        arrayOf(Manifest.permission.ACCESS_FINE_LOCATION),
                        ACCESS_FINE_LOCATION
                )
            } else if (ActivityCompat.checkSelfPermission(
                            mainActivity,
                            Manifest.permission.ACCESS_COARSE_LOCATION
                    ) != PackageManager.PERMISSION_GRANTED
            ) {
                ActivityCompat.requestPermissions(
                        mainActivity,
                        arrayOf(Manifest.permission.ACCESS_COARSE_LOCATION),
                        ACCESS_COARSE_LOCATION
                )
            } else {
                location = locationManager!!.getLastKnownLocation(provider!!)
                //это
                //  location(location);
                //---
                locationManager!!.requestLocationUpdates(provider!!, (60 * 1000).toLong(), 0f, this)
                googleMap!!.isMyLocationEnabled = true

                if (location != null) {
                    try {
                        viewModel.lat = location!!.latitude.toString()
                        viewModel.lng = location!!.longitude.toString()

                    } catch (e: Exception) {
                        e.printStackTrace()
                    }
                }
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    override fun onAttach(context: Context) {
        super.onAttach(context)

        if (context is Activity) {
            this.mainActivity = context as MainActivity
        }

    }

    /**
     * Определение заказов по точкам
     */
    private fun defininingOrders(dots: MutableList<DotX>): List<OrderX> {
        val orders = HashSet<OrderX>()
        dots.forEach {
            val currOrder = allOrders[it.orderId]
            currOrder?.let {
                orders.add(currOrder)
            }
        }
        return orders.toList()
    }

    /**
     * Клик по маркеру кластера
     */
    override fun onClusterClick(cluster: Cluster<DotX>): Boolean {
        val dotList = mutableListOf<DotX>()
        for (dot in cluster.items){
            dotList.add(dot)
        }

        val orders = defininingOrders(dotList)
        viewModel.clearAllButtons()
        viewModel.setType(MapNewTwoViewModel.OrderType.ClusterOrders(), orders)
        showBottomSheetOrders()
        return true
    }

    /**
     * Клик по маркеру Item кластера
     */
    override fun onClusterItemClick(itemCluster: DotX): Boolean {
        val orders = defininingOrders(mutableListOf(itemCluster))
        viewModel.clearAllButtons()
        viewModel.setType(MapNewTwoViewModel.OrderType.SingleOrder(), orders)
        showBottomSheetOrders()
        return true
    }

    fun getItemIcon(dot: DotX): BitmapDescriptor {
        if(Build.VERSION.SDK_INT >= 24) {
            return if(dot.isMyOrder){
                when(dot.type){
                    0 -> vectorToBitmap(R.drawable.ic_take_point_my_order)
                    1 -> vectorToBitmap(R.drawable.ic_middle_point_my_order)
                    else -> vectorToBitmap(R.drawable.ic_delivery_point_my_order)
                }
            } else if(dot.date.toLowerCase() == "сегодня"){
                when(dot.type){
                    0 -> vectorToBitmap(R.drawable.ic_take_point_available_order)
                    1 -> vectorToBitmap(R.drawable.ic_middle_point_available_order)
                    else -> vectorToBitmap(R.drawable.ic_delivery_point_available_order)
                }
            } else {
                when(dot.type){
                    0 -> vectorToBitmap(R.drawable.ic_take_point_available_order_tomorrow)
                    1 -> vectorToBitmap(R.drawable.ic_middle_point_available_order_tomorrow)
                    else -> vectorToBitmap(R.drawable.ic_delivery_point_available_order_tomorrow)
                }
            }
        } else{
            return if(dot.isMyOrder) {
                when (dot.type) {
                    0 -> bitmapDescriptorFromVector(R.drawable.take_point_my_order)
                    1 -> bitmapDescriptorFromVector(R.drawable.middle_point_my_order)
                    else -> bitmapDescriptorFromVector(R.drawable.delivery_point_my_order)
                }
            } else if(dot.date.toLowerCase() == "сегодня"){
                when(dot.type){
                    0 -> bitmapDescriptorFromVector(R.drawable.take_point_available_order)
                    1 -> bitmapDescriptorFromVector(R.drawable.middle_point_available_order)
                    else -> bitmapDescriptorFromVector(R.drawable.delivery_point_available_order)
                }
            } else{

                when(dot.type){
                    0 -> bitmapDescriptorFromVector(R.drawable.take_point_available_order_tomorrow)
                    1 -> bitmapDescriptorFromVector(R.drawable.middle_point_available_order_tomorrow)
                    else -> bitmapDescriptorFromVector(R.drawable.delivery_point_available_order_tomorrow)
                }

            }
        }
    }

    private fun bitmapDescriptorFromVector(@DrawableRes vectorResId: Int): BitmapDescriptor {

        val vectorDrawable: Drawable = ContextCompat.getDrawable(MyApplication.applicationContext(), vectorResId)!!
        vectorDrawable.setBounds(0, 0, vectorDrawable.getIntrinsicWidth(), vectorDrawable.getIntrinsicHeight())
        val bitmap = Bitmap.createBitmap(vectorDrawable.getIntrinsicWidth(), vectorDrawable.getIntrinsicHeight(), Bitmap.Config.ARGB_8888)
        val canvas = Canvas(bitmap)
        vectorDrawable.draw(canvas)
        return BitmapDescriptorFactory.fromBitmap(bitmap)
    }




    private fun vectorToBitmap(@DrawableRes id: Int): BitmapDescriptor {
        val vectorDrawable =
                ResourcesCompat.getDrawable(MyApplication.applicationContext().resources, id, null)!!
        val bitmap = Bitmap.createBitmap(
                vectorDrawable.intrinsicWidth,
                vectorDrawable.intrinsicHeight, Bitmap.Config.ARGB_8888
        )
        val canvas = Canvas(bitmap)
        vectorDrawable.setBounds(0, 0, canvas.width, canvas.height)
        vectorDrawable.draw(canvas)
        return BitmapDescriptorFactory.fromBitmap(bitmap)
    }

    /**
     * Определение заказов, необходимых для перерендеринга polylines
     */
    fun defininingReRenderOrders(dotsNeedRender: HashMap<String, DotXPosition>): HashSet<OrderX> {
        val orders = HashSet<OrderX>()
        /**
         * Определяем заказы
         */
        dotsNeedRender.forEach { dot ->
            val currOrder = allOrders[dot.value.dot.orderId]
            currOrder?.let {
                Log.d("Dot id ${dot.key}", "order ${it.id}")
                orders.add(it)
            }
        }
        Log.d("Перерисовать заказы", orders.map { it.id }.toString())
        return orders
    }


    private fun reRenderClusters(){
        for((_, order) in allOrders.entries){
            /**
             * Удаляем Polyline
             */
            clearPolylineOrder(order)
            renderPolylineOrder(order)
        }
    }

    private fun renderPolylineOrder(order: OrderX) {
        val line = PolylineOptions()
        for(dot in order.dots)
            line.add(allDots[dot.id]!!.position)
        stylePolyline(line, order.isMyOrder)
        val currPolyline = googleMap?.addPolyline(line)
        currPolyline?.let {
            Log.d("Polyline order ${order.id}", "нарисована ${line.points}")
            allPolylines[order.id.toString()] = currPolyline
        }
    }

    private fun clearAllPolylines(){
        Log.d("Clear Polyline Before", allPolylines.size.toString())
        allPolylines.forEach{
            val currPolyline = it.value
            currPolyline.remove()
        }
        allPolylines.clear()
        Log.d("Clear Polyline After", allPolylines.size.toString())
    }


    private fun clearPolylineOrder(order: OrderX) {
        val polyline = allPolylines[order.id.toString()]
        polyline?.let{
            it.remove()
            allPolylines.remove(order.id.toString())
            Log.d("Polyline order ${order.id}", "очищена")
        }
    }

    private fun stylePolyline(polyline: PolylineOptions, isMyOrder: Boolean){
        if(isMyOrder) {
            context?.let{
                polyline.color(ContextCompat.getColor(requireContext(), R.color.colorRed))
            }
            val pattern = listOf(
                    Dash(8F)
            )
            polyline.pattern(pattern)


        }
        else{
            context?.let{
                polyline.color(ContextCompat.getColor(requireContext(), R.color.colorAccent))
            }

            val pattern = listOf(
                    Dash(8F), Gap(8F)
            )
            polyline.pattern(pattern)
        }
        polyline.width(POLYLINE_STROKE_WIDTH_PX.toFloat())
        polyline.jointType(JointType.ROUND)
    }

//    /**
//     * Нужно ли перерендерить точку
//     * false нет
//     * true да
//     */
//    /**
//     * Update. Всегда перерисовываем.
//     * Устанавливаем для точек новые значения
//     */
//    fun setPositionDot(newDotPosition: DotXPosition) : Boolean{
////        if(allDots.containsKey(newDotPosition.dot.id)){
////            val oldDotPosition = allDots[newDotPosition.dot.id]!!
//////            if(oldDotPosition == newDotPosition){
//////                return false
//////            }
////        }
//        allDots[newDotPosition.dot.id] = newDotPosition
//        return true
//
//    }

    fun setChangeClusters(clusters: MutableSet<out Cluster<DotX>>){
        val startTime = System.currentTimeMillis()
        for (cluster in clusters){
            var isCluster = false
            if(cluster.size > COUNT_POINT_FOR_RENDER_IN_CLUSTER)
                isCluster = true

            for (item in cluster.items){
                val dotPosition : DotXPosition
                /**
                 * Если точка в кластере, то для точки устанавливаем координаты кластера
                 */
                if(isCluster) {
                    dotPosition = DotXPosition(item, cluster.position, true)
                    Log.d("Dot ${item.id}", "in cluster ${cluster.size} ${cluster.position}")
                } else {
                    dotPosition = DotXPosition(item, item.position, false)
                    Log.d("Dot ${item.id}", "not in cluster ${cluster.size} ${cluster.position}")
                }
                /**
                 * Переопределеляем координаты
                 */
                allDots[dotPosition.dot.id] = dotPosition
            }
        }
        reRenderClusters()
        Log.d("ReRender (Cluster)", "${System.currentTimeMillis() - startTime} ms")
    }


    private fun moveCamera(latLng: LatLng, height: Float){
        googleMap?.moveCamera(
                CameraUpdateFactory.newLatLngZoom(
                        latLng, height
                )
        )
    }

    private fun getCourierItem(): BitmapDescriptor {
        return bitmapDescriptorFromVector(R.drawable.ic_optimised_cour)
    }



    inner class DotRenderer :
            DefaultClusterRenderer<DotX>(
                    MyApplication.applicationContext(),
                    googleMap,
                    clusterManager
            )
    {
        override fun onBeforeClusterItemRendered(item: DotX, markerOptions: MarkerOptions) {
            super.onBeforeClusterItemRendered(item, markerOptions)
            markerOptions
                    .icon(getItemIcon(item))
        }

        override fun shouldRenderAsCluster(cluster: Cluster<DotX>): Boolean {
            return cluster.size > COUNT_POINT_FOR_RENDER_IN_CLUSTER
        }

        override fun onClusterItemUpdated(item: DotX, marker: Marker) {
            marker.setIcon(getItemIcon(item))
        }

        override fun onClustersChanged(clusters: MutableSet<out Cluster<DotX>>?) {
            super.onClustersChanged(clusters)
            if (clusters != null) {
                setChangeClusters(clusters)
            }
            else{
                Log.d("onClustersChanged", "null")
            }
        }


        override fun onBeforeClusterRendered(cluster: Cluster<DotX>, markerOptions: MarkerOptions) {
            // Draw multiple people.
            // Note: this method runs on the UI thread. Don't spend too much time in here (like in this example).

            super.onBeforeClusterRendered(cluster, markerOptions)
            markerOptions.icon(getClusterIcon(cluster))
        }


        override fun onClusterRendered(cluster: Cluster<DotX>, marker: Marker) {
            marker.setIcon(getClusterIcon(cluster))
        }

        override fun onClusterUpdated(cluster: Cluster<DotX>, marker: Marker) {
            marker.setIcon(getClusterIcon(cluster))
        }

        fun getClusterIcon(cluster: Cluster<DotX>): BitmapDescriptor {
            return if(Build.VERSION.SDK_INT >= 24) {
                when(cluster.size){
                    in 100..1000000 -> vectorToBitmap(R.drawable.ic_100more_vector)
                    in 10..100 -> vectorToBitmap(R.drawable.ic_10more_vector)
                    2 -> vectorToBitmap(R.drawable.ic_2_vector)
                    3 -> vectorToBitmap(R.drawable.ic_3_vector)
                    4 -> vectorToBitmap(R.drawable.ic_4_vector)
                    5 -> vectorToBitmap(R.drawable.ic_5_vector)
                    6 -> vectorToBitmap(R.drawable.ic_6_vector)
                    7 -> vectorToBitmap(R.drawable.ic_7_vector)
                    8 -> vectorToBitmap(R.drawable.ic_8_vector)
                    9 -> vectorToBitmap(R.drawable.ic_9_vector)
                    10 -> vectorToBitmap(R.drawable.ic_10_vector)
                    else -> vectorToBitmap(R.drawable.ic_1_vector)
                }

            } else{
                when(cluster.size){
                    in 100..1000000 -> bitmapDescriptorFromVector(R.drawable.ic_100more)
                    in 10..100 -> bitmapDescriptorFromVector(R.drawable.ic_10more)
                    2 -> bitmapDescriptorFromVector(R.drawable.ic_2)
                    3 -> bitmapDescriptorFromVector(R.drawable.ic_3)
                    4 -> bitmapDescriptorFromVector(R.drawable.ic_4)
                    5 -> bitmapDescriptorFromVector(R.drawable.ic_5)
                    6 -> bitmapDescriptorFromVector(R.drawable.ic_6)
                    7 -> bitmapDescriptorFromVector(R.drawable.ic_7)
                    8 -> bitmapDescriptorFromVector(R.drawable.ic_8)
                    9 -> bitmapDescriptorFromVector(R.drawable.ic_9)
                    10 -> bitmapDescriptorFromVector(R.drawable.ic_10)
                    else -> bitmapDescriptorFromVector(R.drawable.ic_1)
                }
            }
        }
    }

    override fun onLocationChanged(location: Location) {
        this.location = location
        viewModel.lng = location.longitude.toString()
        viewModel.lat = location.latitude.toString()
    }

    override fun onStatusChanged(provider: String?, status: Int, extras: Bundle?) {
    }

    override fun onProviderEnabled(provider: String) {
        this.provider = provider
        checkPermissions()
    }

    private fun showBottomSheetOrders(){
        val bottomSheet = BottomSheetDialogFragmentMap()
        bottomSheet.show(mainActivity.supportFragmentManager, bottomSheet.tag)

    }

    override fun onPause() {
        if (locationManager != null)
            if (ActivityCompat.checkSelfPermission(
                            mainActivity,
                            Manifest.permission.ACCESS_FINE_LOCATION
                    ) == PackageManager.PERMISSION_GRANTED || ActivityCompat.checkSelfPermission(
                            mainActivity,
                            Manifest.permission.ACCESS_COARSE_LOCATION
                    ) == PackageManager.PERMISSION_GRANTED
            ) {
                locationManager!!.removeUpdates(this)
            }
        clearAll()
        googleMap?.clear()
        googleMap = null
        clusterManager = null
        renderer = null
        super.onPause()
    }

    override fun onRequestPermissionsResult(
            requestCode: Int,
            permissions: Array<String>,
            grantResults: IntArray
    ) {
        when (requestCode) {
            ACCESS_COARSE_LOCATION, ACCESS_FINE_LOCATION -> if (grantResults.isNotEmpty() && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                checkPermissions()
            }
        }
    }

    fun checkPermissionsStart(): Boolean {
        return PackageManager.PERMISSION_GRANTED == ActivityCompat.checkSelfPermission(
                mainActivity,
                Manifest.permission.ACCESS_FINE_LOCATION
        )
    }
}
```

#### Stack trace
```
2021-03-24 12:25:23.593 13380-13820/? E/AndroidRuntime: FATAL EXCEPTION: DefaultPool6
    Process: com.app.peshkariki, PID: 13380
    java.lang.NullPointerException
        at com.google.android.libraries.maps.lv.zzj.<init>(ArrayDecoders.java:6)
        at com.google.android.libraries.maps.lv.zzau.zza(GeneratedMessageLite.java:138)
        at com.google.android.libraries.maps.lv.zzau$zzc.zza(GeneratedMessageLite.java:5)
        at com.google.android.libraries.maps.lv.zze.zzb(AbstractParser.java:60)
        at com.google.android.libraries.maps.lv.zze.zza(AbstractParser.java:52)
        at com.google.android.libraries.maps.eq.zzo.zza(RequestUtil.java:39)
        at com.google.android.libraries.maps.eq.zzc.zza(ClientPropertiesController.java:243)
        at com.google.android.libraries.maps.fj.zzi.zza(AsyncGmmServerProtocolRpc.java:158)
        at com.google.android.libraries.maps.fj.zzi.zza(AsyncGmmServerProtocolRpc.java:67)
        at com.google.android.libraries.maps.fj.zzd.run(AsyncGmmServerProtocolRpc.java:6)
        at com.google.android.libraries.maps.fv.zzc.run(CancelableRunnable.java:7)
        at com.google.android.libraries.maps.fv.zzae.run(Task.java:9)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.libraries.maps.fv.zzv.run(GmmThread.java:10)
        at java.lang.Thread.run(Thread.java:764)

```

**Comment by danilshik** [comment]
I'm sorry, it seems to be related to the cards themselves, judging by the issue
https://issuetracker.google.com/issues/148084488
Need add in Proguard 
`-keep, includecode class com.google.android.libraries.maps. ** {*; }
-keep, includecode class com.google.android.apps.gmm. ** {*; }
-keep, includecode class com.google.common.logging. ** {*; }`
