### ISSUE TITLE
Failing tests in release.yml

### ISSUE THREAD

**Issue by arriolac** [googlemaps/android-maps-utils#858]
Release failed to run due to 102 failing tests. See: https://github.com/googlemaps/android-maps-utils/runs/2365872553?check_suite_focus=true

**Comment by barbeau** [comment]
@arriolac It looks like the Gradle plugin got bumped to `4.1.3` by dependabot in https://github.com/googlemaps/android-maps-utils/commit/787006d5cb73439a347fc5ffc6d50cead99f8729 - could this be related to the same issue we saw in https://github.com/googlemaps/android-maps-utils/issues/800 when the build failed on `4.1.0`?

**Comment by arriolac** [comment]
It could be related but looking at the logs, the error seems a bit different.

Not related to this issue but if the build passed due to dependabot bumping the Gradle plugin, should #800 be closed @barbeau ?

**Comment by arriolac** [comment]
Looks like failures are due to Roboelectric:

```
2021-04-19T23:20:00.6610983Z         Caused by:
2021-04-19T23:20:00.6612264Z         org.apache.maven.artifact.resolver.MultipleArtifactsNotFoundException: Missing:
2021-04-19T23:20:00.6613982Z         ----------
2021-04-19T23:20:00.6614713Z         1) org.robolectric:android-all:jar:10-robolectric-5803371
2021-04-19T23:20:00.6615144Z 
2021-04-19T23:20:00.6615638Z           Try downloading the file manually from the project website.
2021-04-19T23:20:00.6616033Z 
2021-04-19T23:20:00.6616597Z           Then, install it using the command: 
2021-04-19T23:20:00.6617751Z               mvn install:install-file -DgroupId=org.robolectric -DartifactId=android-all -Dversion=10-robolectric-5803371 -Dpackaging=jar -Dfile=/path/to/file
2021-04-19T23:20:00.6618468Z 
2021-04-19T23:20:00.6618998Z           Alternatively, if you host your own repository you can deploy the file there: 
2021-04-19T23:20:00.6620395Z               mvn deploy:deploy-file -DgroupId=org.robolectric -DartifactId=android-all -Dversion=10-robolectric-5803371 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
2021-04-19T23:20:00.6621208Z 
2021-04-19T23:20:00.6621571Z           Path to dependency: 
2021-04-19T23:20:00.6622223Z           	1) org.apache.maven:super-pom:pom:2.0
2021-04-19T23:20:00.6633853Z           	2) org.robolectric:android-all:jar:10-robolectric-5803371
2021-04-19T23:20:00.6634306Z 
2021-04-19T23:20:00.6634742Z         ----------
2021-04-19T23:20:00.6635268Z         1 required artifact is missing.
2021-04-19T23:20:00.6635578Z 
2021-04-19T23:20:00.6635912Z         for artifact: 
2021-04-19T23:20:00.6636723Z           org.apache.maven:super-pom:pom:2.0
2021-04-19T23:20:00.6637091Z 
2021-04-19T23:20:00.6637517Z         from the specified remote repositories:
2021-04-19T23:20:00.6638141Z           central (http://repo1.maven.org/maven2),
2021-04-19T23:20:00.6638887Z           sonatype (https://oss.sonatype.org/content/groups/public/)
2021-04-19T23:20:00.6640829Z             at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:360)
2021-04-19T23:20:00.6643681Z             at org.apache.maven.artifact.ant.DependenciesTask.doExecuteResolution(DependenciesTask.java:263)
2021-04-19T23:20:00.6645425Z             ... 23 more
2021-04-19T23:20:00.6645680Z 
2021-04-19T23:20:00.6646615Z com.google.maps.android.heatmaps.GradientTest > testInterpolateColor STANDARD_OUT
2021-04-19T23:20:00.6649065Z     [Robolectric] com.google.maps.android.heatmaps.GradientTest.testInterpolateColor: sdk=28; resources=BINARY
2021-04-19T23:20:00.6650935Z     Downloading from maven 
2021-04-19T23:20:00.6651249Z 
2021-04-19T23:20:00.6652195Z com.google.maps.android.heatmaps.GradientTest > testInterpolateColor STANDARD_ERROR
2021-04-19T23:20:00.6654686Z     Downloading: org/robolectric/android-all/10-robolectric-5803371/android-all-10-robolectric-5803371.pom from repository sonatype at https://oss.sonatype.org/content/groups/public/
2021-04-19T23:20:00.6657185Z     Error transferring file: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
2021-04-19T23:20:00.6658684Z 
2021-04-19T23:20:00.6659664Z com.google.maps.android.heatmaps.GradientTest > testInterpolateColor STANDARD_OUT
2021-04-19T23:20:00.6670504Z     [WARNING] Unable to get resource 'org.robolectric:android-all:pom:10-robolectric-5803371' from repository sonatype (https://oss.sonatype.org/content/groups/public/): Error transferring file: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
2021-04-19T23:20:00.6672371Z 
2021-04-19T23:20:00.6673968Z com.google.maps.android.heatmaps.GradientTest > testInterpolateColor STANDARD_ERROR
2021-04-19T23:20:00.6676654Z     Downloading: org/robolectric/android-all/10-robolectric-5803371/android-all-10-robolectric-5803371.pom from repository central at http://repo1.maven.org/maven2
2021-04-19T23:20:00.6679194Z     Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/robolectric/android-all/10-robolectric-5803371/android-all-10-robolectric-5803371.pom
2021-04-19T23:20:00.6680241Z 
2021-04-19T23:20:00.6681118Z com.google.maps.android.heatmaps.GradientTest > testInterpolateColor STANDARD_OUT
2021-04-19T23:20:00.6683740Z     [WARNING] Unable to get resource 'org.robolectric:android-all:pom:10-robolectric-5803371' from repository central (http://repo1.maven.org/maven2): Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/robolectric/android-all/10-robolectric-5803371/android-all-10-robolectric-5803371.pom
2021-04-19T23:20:00.6685310Z 
2021-04-19T23:20:00.6686191Z com.google.maps.android.heatmaps.GradientTest > testInterpolateColor STANDARD_ERROR
2021-04-19T23:20:00.6688154Z     Downloading: org/robolectric/android-all/10-robolectric-5803371/android-all-10-robolectric-5803371.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
2021-04-19T23:20:00.6690493Z     Error transferring file: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
2021-04-19T23:20:00.6691722Z 
2021-04-19T23:20:00.6692795Z com.google.maps.android.heatmaps.GradientTest > testInterpolateColor STANDARD_OUT
2021-04-19T23:20:00.6695663Z     [WARNING] Unable to get resource 'org.robolectric:android-all:jar:10-robolectric-5803371' from repository sonatype (https://oss.sonatype.org/content/groups/public/): Error transferring file: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
2021-04-19T23:20:00.6697470Z 
2021-04-19T23:20:00.6698349Z com.google.maps.android.heatmaps.GradientTest > testInterpolateColor STANDARD_ERROR
2021-04-19T23:20:00.6700224Z     Downloading: org/robolectric/android-all/10-robolectric-5803371/android-all-10-robolectric-5803371.jar from repository central at http://repo1.maven.org/maven2
2021-04-19T23:20:00.6702945Z     Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/robolectric/android-all/10-robolectric-5803371/android-all-10-robolectric-5803371.jar
2021-04-19T23:20:00.6704445Z 
2021-04-19T23:20:00.6705369Z com.google.maps.android.heatmaps.GradientTest > testInterpolateColor STANDARD_OUT
2021-04-19T23:20:00.6708395Z     [WARNING] Unable to get resource 'org.robolectric:android-all:jar:10-robolectric-5803371' from repository central (http://repo1.maven.org/maven2): Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/robolectric/android-all/10-robolectric-5803371/android-all-10-robolectric-5803371.jar
```

**Comment by barbeau** [comment]
>Not related to this issue but if the build passed due to dependabot bumping the Gradle plugin, should #800 be closed @barbeau ?

No, I just tested and the demo app still fails - https://github.com/googlemaps/android-maps-utils/issues/800#issuecomment-823408183.
